### ISSUE TITLE
JFoenix can not be used in Java11

### ISSUE THREAD

**Issue by goxr3plus** [jfoenixadmin/JFoenix#1005]
I am getting the below error :

``` JAVA
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix
```

Trying to use JFoenix with Java11

**Comment by DJViking** [comment]
> Guys do you know how i can solve this error with Java11 and JFoenix latest version ?
> 
> ```java
> Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix
> ```
> 
> @mokun @jjyyxx @DJViking
> 
> #1005

Are you getting this in a modularized or non-modularized project?

Running our Non-modularized Java 11 project the usual way we are not getting IllegalAccessException. We have none of the jvm-arguments mentioned by @jjyyxx in #889 , and it works fine without them.
We build and run the application image using jlink and jpackage.

However when running `gradle run`, we do get that IllegalAccessException.
The gradle run task is from the application plugin for easy running the project.

```
Exception in thread "GUIBuilderWorker" java.lang.IllegalAccessError: class com.jfoenix.controls.JFXAutoCompletePopup (in unnamed module @0x69b9c73f) cannot access class com.sun.javafx.stage.PopupWindowHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.stage to unnamed module @0x69b9c73f
        at com.jfoenix.controls.JFXAutoCompletePopup.<init>(JFXAutoCompletePopup.java:68)
        at com.jfoenix.skins.JFXChipViewSkin$ChipsAutoComplete.<init>(JFXChipViewSkin.java:386)
        at com.jfoenix.controls.JFXChipView.<init>(JFXChipView.java:167)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:105)
        at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1154)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:105)
        at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1154)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
```

**Comment by jfoenixadmin** [comment]
@DJViking this is related to #889

**Comment by Ev1dentSnow** [comment]
> > Guys do you know how i can solve this error with Java11 and JFoenix latest version ?
> > ```java
> > Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @mokun @jjyyxx @DJViking
> > #1005
> 
> Are you getting this in a modularized or non-modularized project?
> 
> Running our Non-modularized Java 11 project the usual way we are not getting IllegalAccessException. We have none of the jvm-arguments mentioned by @jjyyxx in #889 , and it works fine without them.
> We build and run the application image using jlink and jpackage.
> 
> However when running `gradle run`, we do get that IllegalAccessException.
> The gradle run task is from the application plugin for easy running the project.
> 
> ```
> Exception in thread "GUIBuilderWorker" java.lang.IllegalAccessError: class com.jfoenix.controls.JFXAutoCompletePopup (in unnamed module @0x69b9c73f) cannot access class com.sun.javafx.stage.PopupWindowHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.stage to unnamed module @0x69b9c73f
>         at com.jfoenix.controls.JFXAutoCompletePopup.<init>(JFXAutoCompletePopup.java:68)
>         at com.jfoenix.skins.JFXChipViewSkin$ChipsAutoComplete.<init>(JFXChipViewSkin.java:386)
>         at com.jfoenix.controls.JFXChipView.<init>(JFXChipView.java:167)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>         at java.base/java.lang.Class.newInstance(Class.java:584)
>         at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
>         at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
>         at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
>         at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:105)
>         at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1154)
>         at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
>         at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
>         at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:105)
>         at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1154)
>         at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
>         at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
>         at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
> ```

How would you use this/apply this to a modularized project?

**Comment by DJViking** [comment]
We have the same problem using the application plugin `gradle run`.
The solution was to define `--add-opens`, and `--add-exports` for these modules on the run task.

```
run {
    doFirst {
        jvmArgs = {
            '--module-path', classpath.asPath,
            '--add-modules', 'javafx.graphics',
            '--add-opens', 'javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED',
            '--add-exports', 'javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED',
        }
     }
}
```
