### ISSUE TITLE
Exception on importing JFoenix into JavaFX Scene Builder 8.1.1

### ISSUE THREAD

**Issue by weahoo** [jfoenixadmin/JFoenix#103]
Hello,

thanks for this impressive JavaFX enhancement. But when I tried to import the components into Scene Builder(version 8.1.1), the following exception displayed on JAR analysis reporter, this exception caused another issue: After saving the JFoenix components into fxml, and it cannot be opened again after closing it. May I know how to resolve it?
The next section is the exception trace:
`Exception for: com/jfoenix/controls/JFXDecorator.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.controls.JFXDecorator

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.controls.JFXDecorator.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXColorPalette.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXColorPalette

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXColorPalette.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXColorPickerUI.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXColorPickerUI

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXColorPickerUI.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXCustomColorPicker.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1013)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.IllegalAccessException: Class sun.reflect.misc.ReflectUtil can not access a member of class com.jfoenix.skins.JFXCustomColorPicker with modifiers "public"

	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)

	at java.lang.Class.newInstance(Class.java:436)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Exception for: com/jfoenix/skins/JFXCustomColorPickerDialog.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXCustomColorPickerDialog

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXCustomColorPickerDialog.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXDatePickerContent.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXDatePickerContent

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXDatePickerContent.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXNestedTableColumnHeader.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXNestedTableColumnHeader

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXNestedTableColumnHeader.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXTableColumnHeader.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXTableColumnHeader

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXTableColumnHeader.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/skins/JFXTimePickerContent.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.skins.JFXTimePickerContent

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.skins.JFXTimePickerContent.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

Exception for: com/jfoenix/svg/SVGGlyph.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)

	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:103)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1011)

	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)

	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)

	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)

	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:299)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:122)

	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:88)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.InstantiationException: com.jfoenix.svg.SVGGlyph

	at java.lang.Class.newInstance(Class.java:427)

	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)

	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)

	... 11 more

Caused by: java.lang.NoSuchMethodException: com.jfoenix.svg.SVGGlyph.<init>()

	at java.lang.Class.getConstructor0(Class.java:3082)

	at java.lang.Class.newInstance(Class.java:412)

	... 13 more

`

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for your comment, we are aware of these issues regarding scene builder integration.
Please note that only the basic components are compatible with scene builder for now.
this issue is related to #100 

Regards,

**Comment by weahoo** [comment]
I tried to import the JFXButton only into the scene builder, but it seems the given exception still occurred. And I compare the behavior of Scene Builder by Gluon and Scene Builder 2.0 from Oracle, the same exceptions occurred, the Gluon version failed to reopen the fxml, while the Oracle one can open it again.

**Comment by jfoenixadmin** [comment]
this issue is related to #105 , and its related to scene builder.

you can open an issue using the following link:
https://bitbucket.org/gluon-oss/scenebuilder/issues/new

**Comment by nacyst** [comment]
Hey, I have JDK 1.8 and using Jfoenix 8.0.8 and I still have a problem with opening my JAR file it's can't load a fxml file because Exception is Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton

**Comment by MdSarfarazAlam** [comment]
Hey, I have JDK 11 and using Jfoenix 9.0.8 and I have imported  my Jfoenix 9.0.8.jar file with scene Builder and  when i am using JFXButton  and running program getting > Exception is Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton.

**Comment by Grenndalf** [comment]
Seems like i am not the only one. In my case after building executable Jar with maven (maven -> Plugins jar jar:jar) i go to the view containing JFX element and app crushing saying: 
1. Caused by: java.lang.NoClassDefFoundError: com/jfoenix/controls/JFXButton 
2. Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton
        at java.net.URLClassLoader.findClass(Unknown Source)
Unknown source shows many times as a reason.
Additionally i ve tried to add jfoenix to jar-with-dependencies, tried to add jfoenix.jar as a global library. Nothing helps.

I am using java 8 with proper jfoenix version.
At this moment i think i have to rebuild my application with standard controls and other elements. Really bad cause i like jfoenix a lot but it is unusable :(

**Comment by RoxannaS** [comment]
Hi! Currently, I am facing the same issue. There is a fix for it?
