### ISSUE TITLE
connot resolve far-user

### ISSUE THREAD

**Issue by qq490804899** [jfoenixadmin/JFoenix#1034]
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.datafx.controller.flow.FlowException: io.datafx.controller.FxmlLoadException: Can't create controller for class class com.clhysdk.packtool.gui.main.MainController
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:149)
	at com.clhysdk.packtool.Main.start(Main.java:49)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: io.datafx.controller.FxmlLoadException: Can't create controller for class class com.clhysdk.packtool.gui.main.MainController
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:201)
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:146)
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot call Method: public void com.clhysdk.packtool.gui.main.MainController.init() throws java.lang.Exception
	at io.datafx.core.DataFXUtils$3.run(DataFXUtils.java:100)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.datafx.core.DataFXUtils.callPrivileged(DataFXUtils.java:92)
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:196)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.datafx.core.DataFXUtils$3.run(DataFXUtils.java:98)
	... 11 more
Caused by: javafx.fxml.LoadException: 
file:/Users/xielinhua/Downloads/Projects/pro_server/xlsdkpace/target/apk_pack-jar-with-dependencies.jar!/fxml/ui/popup/MainPopup.fxml:13

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.clhysdk.packtool.gui.main.MainController.init(MainController.java:85)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:262)
	at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:54)
	at javafx.fxml.FXMLLoader$Element.applyProperty(FXMLLoader.java:512)
	at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:363)
	at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325)
	at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:258)
	... 27 more
Caused by: java.lang.UnsupportedOperationException: Cannot resolve 'far-user'
	at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:60)
	at org.kordamp.ikonli.javafx.FontIcon.setIconLiteral(FontIcon.java:252)
	... 37 more

**Comment by jfoenixadmin** [comment]
will close this issue as the exception is not related to JFoenix.
