### ISSUE TITLE
StyleableDoubleProperty ClassNotFoundException

### ISSUE THREAD

**Issue by jakeingit** [jfoenixadmin/JFoenix#104]
When using Scenebuilder, I can launch a standard JavaFx .fxml layout just fine. But if I add just one JFoenix element, it causes this exception. I imported the JFoenix jar into IntelliJ IDEA 15's libraries and that allows me to import the JFoenix.controls from the library for the .fxml.

Everything compiles, but there is something I'm missing here.

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:403)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.**NoClassDefFoundError: javafx/css/StyleableDoubleProperty**
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
	at java.lang.Class.getConstructor0(Class.java:2803)
	at java.lang.Class.getConstructor(Class.java:1718)
	at sun.reflect.misc.ConstructorUtil.getConstructor(ConstructorUtil.java:38)
	at javafx.fxml.JavaFXBuilderFactory.getBuilder(JavaFXBuilderFactory.java:121)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:805)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:565)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2348)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2164)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2061)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2778)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2757)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2743)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2730)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2719)
	at ExcelInterface.start(ExcelInterface.java:33)
	at com.sun.javafx.application.LauncherImpl$5.run(LauncherImpl.java:319)
	at com.sun.javafx.application.PlatformImpl$5.run(PlatformImpl.java:216)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:176)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:176)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$100(WinApplication.java:17)
	at com.sun.glass.ui.win.WinApplication$3$1.run(WinApplication.java:67)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javafx.css.StyleableDoubleProperty
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 28 more

**Comment by jakeingit** [comment]
I should also say, I am executing this from just using run> in the IDE...

**Comment by jfoenixadmin** [comment]
i think this is related to your project class path not JFoenix
