### ISSUE TITLE
 NPE JFXDatePicker JDK13

### ISSUE THREAD

**Issue by Bodyash** [jfoenixadmin/JFoenix#1059]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.controls.JFXDatePicker.initialize(JFXDatePicker.java:84)
	at com.jfoenix.controls.JFXDatePicker.<init>(JFXDatePicker.java:62)

JDK13 x64 Arch Linux

On JDK 11 everything fine

**Comment by jfoenixadmin** [comment]
it's resolved in 2c219040b31d98a1629168a77152178090125ec9
