### ISSUE TITLE
i have a problem with jfoenix it gives me some errors 

### ISSUE THREAD

**Issue by sarah898989** [jfoenixadmin/JFoenix#1114]
hello i have this project that is due to saturday and i'm struggling with two components in jfoenix datepicker and timepicker. i looked in similar questions but in vain i still get errors.
ps: I couldn't type the whole error
I would really appreciate any help with this.
I kind of sound desperate with this because I really am. I am new with jfoenix and javafx and all I want now is for this to work. Please help
up
UP
UP
UP 
UP
UP
 

```
 ```
  ```
 Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at 
```javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8148)
    	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8201)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:4026)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Scene.java:4048)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	.............
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	.......
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140).......
    Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x3808f28b) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x3808f28b
    	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:62)
    	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
    	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
    	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
    	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
    	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
    	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
    	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
    	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
    	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
    	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
    	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
    	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
    	at javafx.graphics/javafx.scene.Scene.access$3400(Scene.java:172)
    	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2477)
    	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
    	at java.base/java.security.AccessController.doPrivileged(Native Method)
    	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
    	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
    	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    	at java.base/java.lang.Thread.run(Thread.java:834)

```
```

So I did try to work with these vm arguments

   ```
 --module-path "C:\Users\acer\Documents\lib\javafx-sdk-11.0.2\lib" --add-modules=javafx.controls,javafx.fxml
    
    --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED"
    --add-exports=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED"
    --add-exports=javafx.base/com.sun.javafx.binding=ALL-UNNAMED"
    --add-exports=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED"
    --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED"
```


i got these warnings at first

    WARNING: Unknown module: ALL-UNNAMED
          --add-exports=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED specified to --add-exports
    WARNING: Unknown module: ALL-UNNAMED
           --add-exports=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED specified to --add-exports

Than i got this error

  ```
  Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
    	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
    	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8879)
    	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
    	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
    	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
    	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
    	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
    	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
    	at java.base/java.security.AccessController.doPrivileged(Native Method)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
    	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.reflect.InvocationTargetException
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
    	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
    	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
    	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
    	... 47 more
    Caused by: java.lang.IllegalAccessError: class com.jfoenix.skins.JFXGenericPickerSkin (in unnamed module @0x430ae461) cannot access class com.sun.javafx.binding.ExpressionHelper (in module javafx.base) because module javafx.base does not export com.sun.javafx.binding to unnamed module @0x430ae461
    	at com.jfoenix.skins.JFXGenericPickerSkin.removeParentFakeFocusListener(JFXGenericPickerSkin.java:124)
    	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:64)
    	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
    	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
    	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
    	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
    	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
    	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
    	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
    	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
    	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
    	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
    	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
    	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
    	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
    	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
    	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
    	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
    	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
    	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
    	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
    	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
    	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
    	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
    	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
    	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
    	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1745)
    	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
    	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
    	at javafx.graphics/javafx.stage.Window$SceneModel.invalidated(Window.java:814)
    	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
    	at javafx.graphics/javafx.stage.Window.setScene(Window.java:770)
    	at javafx.graphics/javafx.stage.Stage.setScene(Stage.java:266)
    	at application.GroupPanel2.Push(GroupPanel2.java:204)
    	... 58 more
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    
    Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXGenericPickerSkin (in unnamed module @0x430ae461) cannot access class com.sun.javafx.binding.ExpressionHelper (in module javafx.base) because module javafx.base does not export com.sun.javafx.binding to unnamed module @0x430ae461
    	at com.jfoenix.skins.JFXGenericPickerSkin.removeParentFakeFocusListener(JFXGenericPickerSkin.java:124)
    	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:64)
    	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
    	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
    	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
    	......
    Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXGenericPickerSkin (in unnamed module @0x430ae461) cannot access class com.sun.javafx.binding.ExpressionHelper (in module javafx.base) because module javafx.base does not export com.sun.javafx.binding to unnamed module @0x430ae461
    	at com.jfoenix.skins.JFXGenericPickerSkin.removeParentFakeFocusListener(JFXGenericPickerSkin.java:124)
    	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:64)
    	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
    	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
    	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
    	.....
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8148)
    	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8201)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:4026)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Scene.java:4048)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
    	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
    	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
    	at javafx.graphics/javafx.stage.Window.setFocused(Window.java:674)
    	at javafx.graphics/javafx.stage.Window$1.setFocused(Window.java:149)
    	at javafx.graphics/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
    	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:64)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
    	at java.base/java.security.AccessController.doPrivileged(Native Method)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
    	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1346)
    	at javafx.graphics/com.sun.glass.ui.Window.notifyFocus(Window.java:1325)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: class com.jfoenix.controls.FakeFocusJFXTextField cannot be cast to class com.sun.javafx.scene.control.FakeFocusTextField (com.jfoenix.controls.FakeFocusJFXTextField is in unnamed module of loader 'app'; com.sun.javafx.scene.control.FakeFocusTextField is in module javafx.controls of loader 'app')
    	at javafx.controls/javafx.scene.control.skin.ComboBoxPopupControl.lambda$new$2(ComboBoxPopupControl.java:140)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8148)
    	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8201)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:4026)
    	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Scene.java:4048)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
    	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
    	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
    	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
    	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
    	at javafx.graphics/javafx.stage.Window.setFocused(Window.java:674)
    	at javafx.graphics/javafx.stage.Window$1.setFocused(Window.java:149)
    	at javafx.graphics/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
    	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:64)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
    	at java.base/java.security.AccessController.doPrivileged(Native Method)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
    	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
    	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1346)
    	at javafx.graphics/com.sun.glass.ui.Window.notifyFocus(Window.java:1325)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.jfoenix.skins.JFXGenericPickerSkin (in unnamed module @0x430ae461) cannot access class com.sun.javafx.binding.ExpressionHelper (in module javafx.base) because module javafx.base does not export com.sun.javafx.binding to unnamed module @0x430ae461
    	at com.jfoenix.skins.JFXGenericPickerSkin.removeParentFakeFocusListener(JFXGenericPickerSkin.java:124)
    	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:64)
    	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
    	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
    	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
    	
```

**Comment by AlQa-hOlic** [comment]
Seems like something is wrong with your build setup.
Since you are in a hurry, I’d like to recommend [gradle](https://docs.gradle.org/current/userguide/getting_started.html). Check out [the javafx docs](https://openjfx.io/openjfx-docs/#gradle), clone their repo and copy this [directory](https://github.com/openjfx/samples/tree/master/HelloFX/Gradle/hellofx)

Copy all your code into `src/main/java` folder, replacing `HelloFX` class with your Application class.
Change the `mainClassName` in the [build.gradle](https://github.com/openjfx/samples/blob/master/HelloFX/Gradle/hellofx/build.gradle), so that it points to your Application class (Eg: 'some.package.MyApplication')
You can edit the javafx modules [here](https://github.com/openjfx/samples/blob/master/HelloFX/Gradle/hellofx/build.gradle#L12)
And then you can run this gradle application from the commandline: `gradlew run` or however your IDE handles it

**Comment by sarah898989** [comment]
@AlQa-hOlic  First of all thank you so much for replaying i genuinely appreciate it . The truth is I don't know anything about gradle. I guess by following the steps you've given it will become a gradle application. I'm kind of scared if I would be able to make it work. I currently work with eclipse. and javafx sdk 11. Now I'm just wondering if there's a short cut like something I can do just in the settings in eclipse. Sorry and Thank you again. if there isn't I guess I will try this gradle thing

**Comment by AlQa-hOlic** [comment]
@sarah898989 First of all, you should **close this issue** since it is not at all related to the JFeonix library. 
I am not familiar with eclipse. And eclipse has support for gradle. So working with gradle makes sure your project works everywhere (as long as you have a jdk and gradle installed, irrespective of the IDE).
I made a [template](https://github.com/AlQa-hOlic/javafx-gradle-jfeonix-template) repo for your reference. Imagine not having to add vm args every time you run your builds.
Sorry for being insistent on using gradle. Maybe this is the motivation you need, learn a build tool.

**Comment by sarah898989** [comment]
@AlQa-hOlic  Thank you so much for your help and the motivation and the template. I will try to learn it. Again thank you a lot.

**Comment by sarah898989** [comment]
@AlQa-hOlic  I do hope I am not being too annoying. Promise last question. what should I do exactly with this template? Clone it and import it in eclipse and then copying my project into it and then run it, would it work that way ? also i don't have jdk i guess i should download java jdk 11?

**Comment by AlQa-hOlic** [comment]
@sarah898989 yes clone and import the project..
I think you already have a JDK installed and versions can be adjusted. Everything is in the `build.gradle` file. `sourceCompatibility` is the java version and javafx version is inside it's configuration block. Here is a [tutorial](https://www.vogella.com/tutorials/EclipseGradle/article.html#import-an-existing-gradle-project)

**Comment by sarah898989** [comment]
@AlQa-hOlic  Okaay. Thank youu so much for everything!
