### ISSUE TITLE
JFXTabPane Generating Exception

### ISSUE THREAD

**Issue by Nanakwame68** [jfoenixadmin/JFoenix#1147]
I am working on a project using JavaFX and Scene Builder. But when I add  JFXTabPane to the Scene, I get  the following  Runtime Exception which I cannot figure out the cause.

> java.lang.ClassCastException: class com.sun.javafx.geom.BoxBounds cannot be cast to class com.sun.javafx.geom.RectBounds (com.sun.javafx.geom.BoxBounds and com.sun.javafx.geom.RectBounds are in module javafx.graphics of loader 'app')
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.applyTransform(NGNode.java:2484)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.accumulateGroupDirtyRegion(NGNode.java:1226)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.accumulateDirtyRegions(NGNode.java:1041)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.accumulateGroupDirtyRegion(NGNode.java:1208)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.accumulateDirtyRegions(NGNode.java:1041)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:248)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:832)
Am using JavaFX15
Windows 10 64bit
SceneBuilde 10

I need help on how to resolve this issue

**Comment by jfoenixadmin** [comment]
which JFoenix version are you using?

**Comment by Nanakwame68** [comment]
jfoenix-9.0.10

**Comment by Nanakwame68** [comment]
am using version 9.0.10.
