### ISSUE TITLE
Jfoenix dependency illegal reflective access with java 11

### ISSUE THREAD

**Issue by alittwin** [jfoenixadmin/JFoenix#1170]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/C:/Users/Albon/.m2/repository/com/jfoenix/jfoenix/9.0.10/jfoenix-9.0.10.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)
WARNING: Please consider reporting this to the maintainers of com.jfoenix.adapters.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I get this error while trying to load an fxml parent with jfoenix components. Application still works after this problem, but i'm not sure if i should just ignore it because i'm making a bigger project. Do you know what could cause it and how to fix it?

**Comment by sshahine** [comment]
Well, it's because JFoenix is using reflection to access some private methods/fields of the original JavaFX controls. To fix this issue, some changes need to be done from JavaFX side to allow more flexibility in customizing the controls.

**Comment by soarteam** [comment]
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
io.datafx.controller.flow.FlowException: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:143)
	at com.QYun.SuperSpineViewer.Main.start(Main.java:44)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:180)
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:140)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:175)
	... 12 more
Caused by: java.lang.IllegalAccessError: class com.jfoenix.controls.JFXTooltip (in unnamed module @0x153f5a29) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x153f5a29
	at com.jfoenix.controls.JFXTooltip.<init>(JFXTooltip.java:376)
	at com.QYun.SuperSpineViewer.GUI.MainController.init(MainController.java:53)
	... 17 more

**Comment by soarteam** [comment]
I think I also have the same problems.
Should I ignore or do something?

**Comment by m0squito** [comment]
Does it mean that it could potentially become incompatible with a future release of JavaFX? Or do you expect that a future release will open up the API?

**Comment by sshahine** [comment]
I doubt that would happen. But in any case, I'll create a ticket for JavaFX to open up some internal API.

**Comment by Ulathar** [comment]
Having a similar problem:
`java.lang.IllegalAccessException: class com.jfoenix.skins.JFXTextFieldSkin (in module com.jfoenix) cannot access a member of class javafx.scene.control.skin.TextFieldSkin (in module javafx.controls) with modifiers "private"`

Already tried adding 
`--add-opens javafx.controls/javafx.scene.control.skin=com.jfoenix`

as JRE JVM Runtimeparameter without success.
Running on AdoptOpenJDK 11 (J9).

What is the right way to handle this? Especially looking forward to upcomming JDK releases.

**Comment by RocketMaDev** [comment]
Could anyone tell me which class caused this warning? I want to try to fix it. (Low possibility to work it out)

**Comment by louhy** [comment]
@RocketMaDev You'd probably have to set a breakpoint in it to see the full picture (I'm sure it depends on what component you're using), but if you mean the ReflectionHelper class mentioned in the OP (which maybe you couldn't find)... it's only in the 9.0.0 branch (not master). 

https://github.com/sshahine/JFoenix/blob/JFoenix-9.0.0/jfoenix/src/main/java/com/jfoenix/adapters/ReflectionHelper.java

**Comment by louhy** [comment]
Actually I'm not sure if this can be fixed without some drastic measures, this static block is the first one hit, and there's lots of other calls to setAccessible below in ReflectionHelper. Doesn't look too promising for a fix without a lot of work. 

```
/**
 * This class is for breaking the module system of Java 9.
 *
 * @author huang
 */
public class ReflectionHelper {

//    private static Unsafe unsafe = null;
//    private static long objectFieldOffset;
    private static Method accessible0;

    static {
        try {
//            unsafe = AccessController.doPrivileged((PrivilegedExceptionAction<Unsafe>) () -> {
//                Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");
//                theUnsafe.setAccessible(true);
//                return (Unsafe) theUnsafe.get(null);
//            });
//            Field overrideField = AccessibleObject.class.getDeclaredField("override");
//            objectFieldOffset = unsafe.objectFieldOffset(overrideField);
            accessible0 = AccessibleObject.class.getDeclaredMethod("setAccessible0", boolean.class);
            accessible0.setAccessible(true);
        } catch (Throwable ex) {
            ex.printStackTrace();
        }
    }
```

**Comment by Pramudz** [comment]
did anyone come up with any solution for this ?

**Comment by louhy** [comment]
> did anyone come up with any solution for this ?

I don't think there's really any "one" solution, it depends on the error. There's a few other issues filed here about it. Also I've read that there's a more modern version of this library: https://github.com/palexdev/MaterialFX  (Haven't tried it yet.)
