### ISSUE TITLE
[FxmlLoadException] java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by soarteam** [jfoenixadmin/JFoenix#1172]
I'm woring on Java15 and OpenJFX 15, and I try to run JFoenix demo and I got this, and App not working well.  

Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
io.datafx.controller.flow.FlowException: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:143)
	at com.QYun.SuperSpineViewer.Main.start(Main.java:44)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:180)
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:140)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:175)
	... 12 more
Caused by: io.datafx.controller.flow.FlowException: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:143)
	at com.QYun.SuperSpineViewer.GUI.MainController.init(MainController.java:96)
	... 17 more
Caused by: io.datafx.controller.FxmlLoadException: java.lang.reflect.InvocationTargetException
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:180)
	at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:140)
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:175)
	... 19 more
Caused by: java.lang.NullPointerException: context
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.QYun.SuperSpineViewer.GUI.SideMenuController.init(SideMenuController.java:96)
	... 24 more

**Comment by sshahine** [comment]
Well, JFoenix demo is only for Java 8
