### ISSUE TITLE
 Why is there a lack of some methods in the source code that have passed the compilation?

### ISSUE THREAD

**Issue by lx971107** [jfoenixadmin/JFoenix#1253]
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: com.jfoenix.skins.JFXDatePickerSkin.getEditableInputNode()Ljavafx/scene/control/TextField;
	at com.jfoenix.skins.JFXDatePickerSkin.getDisplayNode(JFXDatePickerSkin.java:211)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.updateDisplayArea(ComboBoxBaseSkin.java:141)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.computePrefWidth(ComboBoxBaseSkin.java:183)
	at javafx.scene.control.Control.computePrefWidth(Control.java:535)
	at javafx.scene.Parent.prefWidth(Parent.java:904)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at javafx.scene.layout.Region.computeChildPrefAreaWidth(Region.java:1728)
	at javafx.scene.layout.HBox.getAreaWidths(HBox.java:457)
	at javafx.scene.layout.HBox.layoutChildren(HBox.java:627)
	at javafx.scene.Parent.layout(Parent.java:1076)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Parent.layout(Parent.java:1082)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
	at com.sun.javafx.tk.Toolkit$$Lambda$233/586852392.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$40/1603637147.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$36/674483268.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lx971107** [comment]
![image](https://user-images.githubusercontent.com/75794971/212462689-7680067d-feef-40a8-beec-20066e8f52e7.png)
