### ISSUE TITLE
JFXDatePicker not appearing in Scene Builder with JFoenix 9.0.10 and Scene Builder 19.0.0 (Java 20), despite other components working

### ISSUE THREAD

**Issue by omdamahe** [jfoenixadmin/JFoenix#1258]
"I'm using JFoenix 9.0.10 and Scene Builder 19.0.0 for a Java project, but the JFXDatePicker component is not showing up in Scene Builder's search bar. I've already imported the JFoenix library and refreshed the component list, but to no avail. Other JFoenix components are working properly. I'm using the latest version of Java. How can I fix this issue?"

Accompanied by these two screenshots:

[Screenshot of Scene Builder with the missing JFXDatePicker component](https://i.stack.imgur.com/q6rJX.png)
[Screenshot of the import section with the imported JFoenix library](https://i.stack.imgur.com/z4LVe.png)

And here is Scene Builder Versions
![image](https://user-images.githubusercontent.com/56194076/235336671-c9958ec8-d95d-4449-8ebb-05e23aace7c7.png)

**Comment by abdummm** [comment]
I am having the same issue

**Comment by geofromkc** [comment]
Any update on this?  Have run into the same using the following:

Product Version
JavaFX Scene Builder 24.0.1

Build Information
Version 24.0.1
Date: 2025-07-03 08:59:00
JavaFX Version: 24.0.1
Java Version: 22, OpenJDK Runtime Environment

------------------------------------------------------

jfoenix-9.0.10

**Comment by geofromkc** [comment]
Found a recent post suggesting jfoenix 9.0.1 as a solution.   Nope.

**Comment by abdummm** [comment]
I stopped using Scene Builder all together and would build my app to see how it would look

**Comment by geofromkc** [comment]
So I defined  JFXDatePicker in my controller code:
JFXDatePicker jfd = new JFXDatePicker();

Resulted in:
java.lang.reflect.InaccessibleObjectException: Unable to make boolean java.lang.reflect.AccessibleObject.setAccessible0(boolean) accessible: module java.base does not "opens java.lang.reflect" to module com.jfoenix
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:353)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:329)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:277)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:182)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:176)
	at com.jfoenix/com.jfoenix.adapters.ReflectionHelper.<clinit>(ReflectionHelper.java:48)
	at com.jfoenix/com.jfoenix.controls.JFXDatePicker.initialize(JFXDatePicker.java:76)
        ...
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.beans.property.ReadOnlyObjectWrapper.set(Object)" because "editor" is null
	at com.jfoenix/com.jfoenix.controls.JFXDatePicker.initialize(JFXDatePicker.java:84)
        ...

Which would lead one to think that there's a way to make com.jfoenix accessible to java.base.  So I added the following to my Eclipse vm arguments (lots of trial and error):

--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix 
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix 
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix 
--add-opens java.base/java.lang.reflect=com.jfoenix

Still getting some weird exceptions, but the JFXDatePicker is on my pane and does appear to work.
