### ISSUE TITLE
SceneBuilder not opening FXML files

### ISSUE THREAD

**Issue by H-Lo** [jfoenixadmin/JFoenix#1263]
**Java:**
11.0.19 2023-04-18 LTS

**SceneBuilder:**
Version 20.0.0
Date: 2023-05-08 14:08:52
JavaFX Version: 20.0.1
Java Version: 20, OpenJDK Runtime Environment

**JFoenix:**
jfoenix-8.0.10.jar
jfoenix-9.0.10.jar
jfoenix-17.0.2.jar
jfoenix-17.0.5.jar
jfoenix-19.0.1.jar
(none of those is working)

When trying to open FXML file, exception is thrown.

What should I do? Is there a way to fix this?

```
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null
	at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109)
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93)
	at javafx.controls@20.0.1/javafx.scene.control.Control.layoutChildren(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.SubScene.layoutPass(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Group.prefWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Group.minWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.computeChildPrefAreaWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.getMaxAreaWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.computeMaxPrefAreaWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.StackPane.computePrefWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.prefWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.prefWidth(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.minWidth(Unknown Source)
	at javafx.controls@20.0.1/javafx.scene.control.skin.ScrollPaneSkin.computeScrollNodeSize(Unknown Source)
	at javafx.controls@20.0.1/javafx.scene.control.skin.ScrollPaneSkin.layoutChildren(Unknown Source)
	at javafx.controls@20.0.1/javafx.scene.control.Control.layoutChildren(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene.preferredSize(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene$2.preferredSize(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.SceneHelper.preferredSize(Unknown Source)
	at javafx.graphics@20.0.1/javafx.stage.Window$12.invalidated(Unknown Source)
	at javafx.base@20.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@20.0.1/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.graphics@20.0.1/javafx.stage.Window.setShowing(Unknown Source)
	at javafx.graphics@20.0.1/javafx.stage.Window.show(Unknown Source)
	at javafx.graphics@20.0.1/javafx.stage.Stage.show(Unknown Source)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractWindowController.openWindow(AbstractWindowController.java:152)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.openWindow(DocumentWindowController.java:1228)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:675)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:513)
	at com.oracle.javafx.scenebuilder.app.welcomedialog.WelcomeDialogWindowController.handleOpen(WelcomeDialogWindowController.java:221)
	at com.oracle.javafx.scenebuilder.app.welcomedialog.WelcomeDialogWindowController.fireOpenRecentProject(WelcomeDialogWindowController.java:194)
	at com.oracle.javafx.scenebuilder.app.welcomedialog.WelcomeDialogWindowController.lambda$loadAndPopulateRecentItemsInBackground$2(WelcomeDialogWindowController.java:155)
	at javafx.base@20.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@20.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@20.0.1/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@20.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@20.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@20.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@20.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@20.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Tyler-Liquornik** [comment]
Hey, did you ever find a fix to this @H-Lo
