### ISSUE TITLE
JFXDatePicker Does Not Work In Latest Build

### ISSUE THREAD

**Issue by bugembeAndrew** [jfoenixadmin/JFoenix#144]
Hi guys,

I recently downloaded the jfoenix library and discovered that the JFXDatePicker  control does not work. It cannot be dragged and dropped in JavaFX scene builder and causes runtime errors in netbeans IDE.
I am using java version 1.8.0_102. Please help.

**Comment by bugembeAndrew** [comment]
In class JFXDatePickerSkin, the methods getEditableInputNode() and updateDisplayNode() are not defined anywhere in the code. This results in an unusable JFXDatePicker control. Please fix it. I am really in love with your library and want to use it to implement a bunch of beautiful apps.

**Comment by jfoenixadmin** [comment]
Hello, can you provide more details? as we couldn't reproduce this issue.

- please note that the methods getEditableInputNode() and updateDisplayNode() are defined in ComboBoxPopupControl the super class of JFXDatePickerSkin.

- make sure you are using the latest version of scene builder provided by Gluon:
http://gluonhq.com/labs/scene-builder/

**Comment by bugembeAndrew** [comment]
Okay. Let me checkout that scene builder and see

**Comment by bugembeAndrew** [comment]
The latest scene builder from gluon works fine with jfoenix library. Thanks.

**Comment by bugembeAndrew** [comment]
But still the issue I highlighted about JFXDatePickerSkin persists. After designing the UI, the app does not compile. Here is the error stack:

Executing C:\Users\ANDREIS\Documents\NetBeansProjects\JFoenixTest\dist\run2147037524\JFoenixTest.jar using platform C:\Program Files\Java\jdk1.8.0_25\jre/bin/java
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:363)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
	at com.sun.javafx.application.LauncherImpl$$Lambda$48/815033865.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.jfoenix.skins.JFXDatePickerSkin.getEditableInputNode()Ljavafx/scene/control/TextField;
	at com.jfoenix.skins.JFXDatePickerSkin.getDisplayNode(JFXDatePickerSkin.java:203)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.updateDisplayArea(ComboBoxBaseSkin.java:141)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.computePrefWidth(ComboBoxBaseSkin.java:183)
	at javafx.scene.control.Control.computePrefWidth(Control.java:548)
	at javafx.scene.Parent.prefWidth(Parent.java:902)
	at javafx.scene.layout.Region.prefWidth(Region.java:1416)
	at javafx.scene.Node.autosize(Node.java:2861)
	at javafx.scene.Parent.layoutChildren(Parent.java:1103)
	at javafx.scene.Parent.layout(Parent.java:1074)
	at javafx.scene.Parent.layout(Parent.java:1080)
	at javafx.scene.Scene.doLayoutPass(Scene.java:532)
	at javafx.scene.Scene.preferredSize(Scene.java:1612)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1686)
	at javafx.stage.Window$9.invalidated(Window.java:765)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:143)
	at javafx.stage.Window.setShowing(Window.java:841)
	at javafx.stage.Window.show(Window.java:856)
	at javafx.stage.Stage.show(Stage.java:255)
	at jfoenixtest.JFoenixTest.start(JFoenixTest.java:27)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
	at com.sun.javafx.application.LauncherImpl$$Lambda$51/1477303938.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
	at com.sun.javafx.application.PlatformImpl$$Lambda$45/584634336.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/1113261914.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/501263526.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/96639997.run(Unknown Source)
	... 1 more
Exception running application jfoenixtest.JFoenixTest
Java Result: 1

**Comment by bugembeAndrew** [comment]
ComboBoxPopupControl<T> is incomplete. Methods updateDisplayNode() and getEditableInputNode() are not defined in this superclass. Please check the code base to conform.

**Comment by jfoenixadmin** [comment]
please note that you are using an old java version, JFoenix is compatible with Java 1.8.u60 and above.

**Comment by bugembeAndrew** [comment]
I am using java version 1.8.0_102. I believe this is higher than Java 1.8.u60. The other controls compile fine and work alright but when I try the JFXDatePicker the code fails to compile. So I do not think it is the java version if other controls work on it. Please have a look at JFXDatePickerSkin class and its super class to see what am saying.

**Comment by ramprajapat94** [comment]
Yes, the above mentioned problem is even faced by me with JFXDatePicker. Please check.

**Comment by jfoenixadmin** [comment]
plz check the exception you posted, it says "Executing C:\Users\ANDREIS\Documents\NetBeansProjects\JFoenixTest\dist\run2147037524\JFoenixTest.jar using platform C:\Program Files\Java\jdk1.8.0_25\jre/bin/java", maybe you installed Java 1.8.u102 but you are running the application using 1.8.u25.

**Comment by bugembeAndrew** [comment]
Okay. let me fix that and see

**Comment by bugembeAndrew** [comment]
Thanks jfoenixadmin. I changed my netbeans jdkhome to C:\Program Files\Java\jdk1.8.0_102 and the JFXDatePicker control worked. Thanks again!!

**Comment by venusky** [comment]
hello I got the same problem this is my error message:

Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x25104568) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x25104568
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:62)
	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1745)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at app.controls.settingController.btn_add_agent(settingController.java:103)
	... 58 more

how can I solve it?
I love so much your library

**Comment by proSchedule** [comment]
My JFXTimePicker is also not working. I am not able to drag and drop it. Please help me.
