### ISSUE TITLE
Question: Why I get java.lang.NullPointerException

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#162]
Example in your code in the aim to have a hamburger correctly configured:

```
// init the title hamburger icon
		drawer.setOnDrawerOpening((e) -> {
			titleBurger.getAnimation().setRate(1);
			titleBurger.getAnimation().play();
		});
		drawer.setOnDrawerClosing((e) -> {
			titleBurger.getAnimation().setRate(-1);
			titleBurger.getAnimation().play();
		});
		titleBurgerContainer.setOnMouseClicked((e)->{
			if (drawer.isHidden() || drawer.isHidding()) drawer.open();
			else drawer.close();
		});
```

I take exactly the same way:
This is my mainController.java

```
/**
 *
 * @author kevin
 */
public class MainController implements Initializable {
    
    @FXML
    private BorderPane mainBorderPane;

    @FXML
    private VBox mainVBoxTop;

    @FXML
    private JFXToolbar mainToolbarTop;

    @FXML
    private JFXHamburger mainHamburgerTop;

    @FXML
    private JFXDrawer mainDrawer;
    
    @Override
    public void initialize(URL url, ResourceBundle rb) {
     try {
            VBox sideBarPanel = FXMLLoader.load(getClass().getResource("SideBar.fxml"));
            mainDrawer.setSidePane(sideBarPanel);
            
            mainDrawer.setOnDrawerOpening((e) -> {
                System.out.println(mainHamburgerTop);
                System.out.println(mainHamburgerTop.getAnimation());
                mainHamburgerTop.getAnimation().setRate(1);
                mainHamburgerTop.getAnimation().play();
                });
            mainDrawer.setOnDrawerClosing((e) -> {
                mainHamburgerTop.getAnimation().setRate(-1);
                mainHamburgerTop.getAnimation().play();
            });

            mainHamburgerTop.setOnMouseClicked((e)->{
                    if (mainDrawer. isHidden() || mainDrawer.isHidding()) mainDrawer.open();
                    else mainDrawer.close();
            });
            
        } catch (IOException ex) {
            Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
}
```
My JAVA error:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at maxifilmfxml.MainController.lambda$null$0(MainController.java:59)
	at com.jfoenix.controls.JFXDrawer.lambda$initListeners$104(JFXDrawer.java:197)
	at com.jfoenix.controls.JFXDrawer.access$lambda$18(JFXDrawer.java)
	at com.jfoenix.controls.JFXDrawer$$Lambda$19.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:106)
	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
	at javafx.css.StyleableDoubleProperty.set(StyleableDoubleProperty.java:82)
	at com.sun.scenario.animation.shared.InterpolationInterval$DoubleInterpolationInterval.interpolate(InterpolationInterval.java:263)
	at com.sun.scenario.animation.shared.SimpleClipInterpolator.interpolate(SimpleClipInterpolator.java:137)
	at com.sun.scenario.animation.shared.TimelineClipCore.start(TimelineClipCore.java:151)
	at javafx.animation.Timeline.impl_start(Timeline.java:195)
	at javafx.animation.Animation.play(Animation.java:912)
	at javafx.animation.Animation.playFrom(Animation.java:869)
	at com.jfoenix.transitions.CachedTransition.interpolate(CachedTransition.java:99)
	at javafx.animation.Transition.impl_playTo(Transition.java:210)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at maxifilmfxml.MainController.lambda$null$1(MainController.java:63)
	at com.jfoenix.controls.JFXDrawer.lambda$initListeners$105(JFXDrawer.java:204)
	at com.jfoenix.controls.JFXDrawer.access$lambda$19(JFXDrawer.java)
	at com.jfoenix.controls.JFXDrawer$$Lambda$20.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:106)
	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
	at javafx.css.StyleableDoubleProperty.set(StyleableDoubleProperty.java:82)
	at com.sun.scenario.animation.shared.InterpolationInterval$DoubleInterpolationInterval.interpolate(InterpolationInterval.java:263)
	at com.sun.scenario.animation.shared.SimpleClipInterpolator.interpolate(SimpleClipInterpolator.java:137)
	at com.sun.scenario.animation.shared.TimelineClipCore.start(TimelineClipCore.java:151)
	at javafx.animation.Timeline.impl_start(Timeline.java:195)
	at javafx.animation.Animation.play(Animation.java:912)
	at javafx.animation.Animation.playFrom(Animation.java:869)
	at com.jfoenix.transitions.CachedTransition.interpolate(CachedTransition.java:99)
	at javafx.animation.Transition.impl_playTo(Transition.java:210)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.ParallelTransition.impl_playTo(ParallelTransition.java:481)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

LINE 59 seems to be: `mainHamburgerTop.getAnimation().setRate(1);`
 `mainHamburgerTop.getAnimation().` returns null

Thanks a lot

**Comment by kevincaradant** [comment]
OK 
I replaced my code by that where I create a animation and I use it after:
```
        try {
            VBox sideBarPanel = FXMLLoader.load(getClass().getResource("SideBar.fxml"));
            mainDrawer.setSidePane(sideBarPanel);
            
            HamburgerBackArrowBasicTransition transition = new HamburgerBackArrowBasicTransition(mainHamburgerTop);
            transition.setRate(-1);
            
            mainDrawer.setOnDrawerOpening((e) -> {
                transition.setRate(1);
                transition.play();
            });
            
            mainDrawer.setOnDrawerClosing((e) -> {
                transition.setRate(-1);
                transition.play();
            });

            mainHamburgerTop.setOnMouseClicked((e)->{
                    if (mainDrawer. isShown() || mainDrawer.isShowing()) {
                        mainDrawer.close();
                    }
                    else 
                        mainDrawer.open();
            });
        } catch (IOException ex) {
            Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
        } 
```

I don't know if it's normal or not about the getAnimation() on the hamburger tool , so I let you @jfoenixadmin to close this issue if necessary ;)
