### ISSUE TITLE
JFXMasonryPane$Layout

### ISSUE THREAD

**Issue by Defenderdragon** [jfoenixadmin/JFoenix#193]
Hello, when i try to use pane he crushed i read issue https://github.com/jfoenixadmin/JFoenix/issues/142 you are advise change building system on gradle, but i don't use ant, gradle or something else and i see this error: 
"C:\Program Files\Java\jdk1.8.0_101\bin\java" -Didea.launcher.port=7534 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;E:\idea_proj\Yuka\out\production\Yuka;C:\Users\Denis\.m2\repository\com\vk\api\sdk\0.2.0\sdk-0.2.0.jar;C:\Users\Denis\.m2\repository\org\apache\logging\log4j\log4j-core\2.5\log4j-core-2.5.jar;C:\Users\Denis\.m2\repository\org\apache\logging\log4j\log4j-api\2.5\log4j-api-2.5.jar;C:\Users\Denis\.m2\repository\org\apache\commons\commons-collections4\4.1\commons-collections4-4.1.jar;C:\Users\Denis\.m2\repository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;C:\Users\Denis\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\Denis\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\Denis\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Denis\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Denis\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Denis\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Denis\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar;E:\JDBC\sqljdbc_6.0\enu\sqljdbc4.jar;E:\JDBC\sqljdbc_6.0\enu\sqljdbc41.jar;E:\JDBC\sqljdbc_6.0\enu\sqljdbc42.jar;C:\Users\Denis\.m2\repository\com\sun\mail\javax.mail\1.5.5\javax.mail-1.5.5.jar;C:\Users\Denis\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Denis\.m2\repository\com\jfoenix\jfoenix\1.0.0\jfoenix-1.0.0.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain sample.Main
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassFormatError: Method getFreeArea in class com/jfoenix/controls/JFXMasonryPane$Layout has illegal modifiers: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.jfoenix.controls.JFXMasonryPane.<init>(JFXMasonryPane.java:239)
	at sample.Main.start(Main.java:20)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more

Process finished with exit code 1

**Comment by Defenderdragon** [comment]
I try it on clean project and have error to, look it [https://yadi.sk/d/mciQcIJUy8sTB](url)

**Comment by jfoenixadmin** [comment]
Hello,

the problem is your javac version, you can check it by running javac -version on cmd.
the javac version must be 1.8 , as the default modifier is used in java 1.8.
to solve the issue, you need to update your system environment variables to point to javac 1.8.

Regards,

**Comment by jfoenixadmin** [comment]
the default modifier has been removed, the fix is not yet pushed to maven or included in the latest jar.
you need to rebuild jfoenix to get the fix. the jfoenix jar will be updated by Nov 15.

Regards,
