### ISSUE TITLE
Cannot properly set background image on JFXButton

### ISSUE THREAD

**Issue by matthew-matvei** [jfoenixadmin/JFoenix#207]
Hi. Firstly thanks for JFoenix, it's breathed some style into my Java application!

Unfortunately I'm unable to set the background image of a JFXButton. The following code I use works for a regular `javafx.scene.control.Button`:

``` java
Button btn = new Button("text");
btn.setBackground(...);
```

Where I set the background in the programmatic way (not using CSS directly) that Roland suggests [here](https://stackoverflow.com/a/29985284/4673645).

However, using the same process with a JFXButton:

``` java
JFXButton btn = new JFXButton("text");
btn.setBackground(...);
```

I get the background image but also the StackTrace below. The fact that `JFXButtonSkin.isJavaDefaultBackground()` fails, I feel that it may have something to do with Java environment variables on my machine conflicting with something JFoenix is doing differently to regular JavaFX. If there is another, preferred way to add a background image with a JFXButton, could you let me know what it is?

Thanks for any help you can give with this issue.

```
Dec 09, 2016 1:03:22 PM javafx.beans.binding.Bindings$6 computeValue
WARNING: Exception while evaluating binding
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at com.jfoenix.skins.JFXButtonSkin.isJavaDefaultBackground(JFXButtonSkin.java:170)
	at com.jfoenix.skins.JFXButtonSkin.lambda$new$250(JFXButtonSkin.java:110)
	at com.jfoenix.skins.JFXButtonSkin.access$lambda$3(JFXButtonSkin.java)
	at com.jfoenix.skins.JFXButtonSkin$$Lambda$6.call(Unknown Source)
	at javafx.beans.binding.Bindings$6.computeValue(Bindings.java:338)
	at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:153)
	at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:50)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:54)
	at javafx.beans.binding.ObjectBinding.addListener(ObjectBinding.java:72)
	at javafx.beans.property.ObjectPropertyBase.bind(ObjectPropertyBase.java:173)
	at javafx.css.StyleableObjectProperty.bind(StyleableObjectProperty.java:75)
	at com.jfoenix.skins.JFXButtonSkin.<init>(JFXButtonSkin.java:108)
	at com.jfoenix.controls.JFXButton.createDefaultSkin(JFXButton.java:91)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at com.jfoenix.skins.JFXButtonSkin.isJavaDefaultBackground(JFXButtonSkin.java:170)
	at com.jfoenix.skins.JFXButtonSkin.<init>(JFXButtonSkin.java:128)
	at com.jfoenix.controls.JFXButton.createDefaultSkin(JFXButton.java:91)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jfoenixadmin** [comment]
Hello,

Thanks for pointing out the issue 👍 , the fix is pushed to github you can get it by downloading the latest version of JFoenix. the fix will be pushed to maven central by the end of the month.

Regards,

**Comment by matthew-matvei** [comment]
Great, thanks!
