### ISSUE TITLE
Using JFoenix from cmd

### ISSUE THREAD

**Issue by artur99** [jfoenixadmin/JFoenix#208]
Hi!
I'm kind of new to Java, I explored a few UI libs, and stopped on this one. And I'd like to be able to work in it without any other software like NetBeans, Eclipse, etc., and do all the work from cmd `javac`, `java`.
I figured out after a while how to include the lib using `javac -cp ".;bin/jfoenix.jar" hiii.java`, but I still get errors when I try to run any of the demos.
For example:
```
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.FlowPane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import com.jfoenix.controls.JFXButton;

public class hiii extends Application {

	
	@Override public void start(Stage stage) {

		FlowPane main = new FlowPane();
		main.setVgap(20);
		main.setHgap(20);
		
		main.getChildren().add(new Button("Java Button"));
		JFXButton jfoenixButton = new JFXButton("JFoenix Button");
		main.getChildren().add(jfoenixButton);
		
		JFXButton button = new JFXButton("Raised Button".toUpperCase());
		button.getStyleClass().add("button-raised");
		main.getChildren().add(button);
		
		JFXButton button1 = new JFXButton("DISABLED");
		button1.setDisable(true);
		main.getChildren().add(button1);
		
		StackPane pane = new StackPane();
		pane.getChildren().add(main);
		StackPane.setMargin(main, new Insets(100));
		pane.setStyle("-fx-background-color:WHITE");
		
		final Scene scene = new Scene(pane, 800, 200);
		scene.getStylesheets().add(hiii.class.getResource("/res/jfoenix-components.css").toExternalForm());
		stage.setTitle("JFX Button Demo");
		stage.setScene(scene);
		stage.show();

	}

	public static void main(String[] args) { launch(args); }
	
}
```
I will get these errors:
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Lau
ncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImp
l.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherIm
pl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(
LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/jfoenix/controls/JFXButton
        at hiii.start(hiii.java:21)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162
(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Platfor
mImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.
java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformI
mpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatch
er.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.ja
va:191)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 10 more
Exception running application hiii
```
And I have no idea how to make it work..

Thank you!

**Comment by jfoenixadmin** [comment]
well to run the java application you need to add jfoenix.jar to the run command
so you should run it using the following command

java -cp .;bin/jfoenix.jar hiii

however the css file path is wrong so you need to fix it or remove it.
overall I do recommend using some IDE instead of using notepad.

Plz note that this issue will be closed as it's not related to JFoenix development.
Regards,
