### ISSUE TITLE
NPE in JFXTreeTableCellSkin

### ISSUE THREAD

**Issue by swftvsn** [jfoenixadmin/JFoenix#224]
The NPE happens in row 93, it seems that `JFXTreeTableRowSkin.disclosureWidthMap` can be null under some circumstances, but it is not checked correctly.

This only happens when the application is bundled to a Mac App using javafx-maven-plugin (https://github.com/javafx-maven-plugin/javafx-maven-plugin). 

And it is fixed using this patch:

```diff --git a/src/com/jfoenix/skins/JFXTreeTableCellSkin.java b/src/com/jfoenix/skins/JFXTreeTableCellSkin.java
index a919c80..7e55774 100644
--- a/src/com/jfoenix/skins/JFXTreeTableCellSkin.java
+++ b/src/com/jfoenix/skins/JFXTreeTableCellSkin.java
@@ -89,8 +89,10 @@
 		}
 
 		if(tableColumn == treeColumn || ((JFXTreeTableColumn<S,T>)tableColumn).isGrouped()){
-			// add in the width of the disclosure node		
-			leftPadding += JFXTreeTableRowSkin.disclosureWidthMap.containsKey(treeTable) ? JFXTreeTableRowSkin.disclosureWidthMap.get(treeTable) : 0;
+			// add in the width of the disclosure node
+			if (JFXTreeTableRowSkin.disclosureWidthMap != null && JFXTreeTableRowSkin.disclosureWidthMap.containsKey(treeTable)) {
+				leftPadding += JFXTreeTableRowSkin.disclosureWidthMap.get(treeTable);
+			}
 		}
 		// adding in the width of the graphic on the tree item
 		leftPadding += treeItem.getGraphic() == null ? 0 : treeItem.getGraphic().prefWidth(height);
```

The full stack trace is as follows:
```
January 13, 2017 9:35:46 AP. javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.111 by JavaFX runtime of version 8.0.102
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXTreeTableCellSkin.leftLabelPadding(JFXTreeTableCellSkin.java:93)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.computePrefWidth(LabeledSkinBase.java:731)
	at com.sun.javafx.scene.control.skin.TableCellSkinBase.computePrefWidth(TableCellSkinBase.java:153)
	at javafx.scene.control.Control.computePrefWidth(Control.java:537)
	at javafx.scene.Parent.prefWidth(Parent.java:915)
	at javafx.scene.layout.Region.prefWidth(Region.java:1419)
	at com.sun.javafx.scene.control.skin.TreeTableViewSkin.resizeColumnToFitContent(TreeTableViewSkin.java:333)
	at com.sun.javafx.scene.control.skin.TreeTableViewSkin.resizeColumnToFitContent(TreeTableViewSkin.java:56)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(TableColumnHeader.java:531)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.updateScene(TableColumnHeader.java:474)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.handlePropertyChanged(TableColumnHeader.java:314)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.lambda$new$49(TableColumnHeader.java:149)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:831)
	at javafx.scene.Node.invalidatedScenes(Node.java:883)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent$1.onChanged(Parent.java:269)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$19(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.scene.control.skin.NestedTableColumnHeader.updateContent(NestedTableColumnHeader.java:487)
	at com.sun.javafx.scene.control.skin.NestedTableColumnHeader.updateTableColumnHeaders(NestedTableColumnHeader.java:317)
	at com.sun.javafx.scene.control.skin.NestedTableColumnHeader.checkState(NestedTableColumnHeader.java:544)
	at com.sun.javafx.scene.control.skin.NestedTableColumnHeader.computePrefHeight(NestedTableColumnHeader.java:427)
	at javafx.scene.Parent.prefHeight(Parent.java:929)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at com.sun.javafx.scene.control.skin.TableHeaderRow.computePrefHeight(TableHeaderRow.java:331)
	at com.sun.javafx.scene.control.skin.TableHeaderRow.computeMinHeight(TableHeaderRow.java:324)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.control.SkinBase.computeMinHeight(SkinBase.java:254)
	at javafx.scene.control.Control.computeMinHeight(Control.java:489)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.AnchorPane.computeHeight(AnchorPane.java:297)
	at javafx.scene.layout.AnchorPane.computeMinHeight(AnchorPane.java:246)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
	at javafx.scene.layout.Region.getMaxAreaHeight(Region.java:1978)
	at javafx.scene.layout.Region.computeMaxMinAreaHeight(Region.java:1851)
	at javafx.scene.layout.StackPane.computeMinHeight(StackPane.java:289)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at com.sun.javafx.scene.control.skin.SplitPaneSkin.computeMinHeight(SplitPaneSkin.java:863)
	at javafx.scene.control.Control.computeMinHeight(Control.java:489)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.AnchorPane.computeHeight(AnchorPane.java:297)
	at javafx.scene.layout.AnchorPane.computeMinHeight(AnchorPane.java:246)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
	at javafx.scene.layout.BorderPane.getAreaHeight(BorderPane.java:618)
	at javafx.scene.layout.BorderPane.computeMinHeight(BorderPane.java:415)
	at javafx.scene.Parent.minHeight(Parent.java:957)
	at javafx.scene.layout.Region.minHeight(Region.java:1401)
	at javafx.scene.layout.BorderPane.layoutChildren(BorderPane.java:485)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXTreeTableCellSkin.leftLabelPadding(JFXTreeTableCellSkin.java:93)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.computeMinLabeledPartWidth(LabeledSkinBase.java:684)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.computeMinWidth(LabeledSkinBase.java:633)
	at javafx.scene.control.Control.computeMinWidth(Control.java:470)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at javafx.scene.control.SkinBase.computeMinWidth(SkinBase.java:216)
	at javafx.scene.control.Control.computeMinWidth(Control.java:470)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at javafx.scene.layout.AnchorPane.computeWidth(AnchorPane.java:274)
	at javafx.scene.layout.AnchorPane.computeMinWidth(AnchorPane.java:242)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at javafx.scene.layout.Region.computeChildMinAreaWidth(Region.java:1667)
	at javafx.scene.layout.Region.getMaxAreaWidth(Region.java:1996)
	at javafx.scene.layout.Region.computeMaxMinAreaWidth(Region.java:1837)
	at javafx.scene.layout.StackPane.computeMinWidth(StackPane.java:282)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at com.sun.javafx.scene.control.skin.SplitPaneSkin.computeMinWidth(SplitPaneSkin.java:846)
	at javafx.scene.control.Control.computeMinWidth(Control.java:470)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at javafx.scene.layout.AnchorPane.computeWidth(AnchorPane.java:274)
	at javafx.scene.layout.AnchorPane.computeMinWidth(AnchorPane.java:242)
	at javafx.scene.Parent.minWidth(Parent.java:943)
	at javafx.scene.layout.Region.minWidth(Region.java:1383)
	at javafx.scene.layout.Region.boundedNodeSizeWithBias(Region.java:1913)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2323)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2238)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2179)
	at javafx.scene.layout.BorderPane.layoutChildren(BorderPane.java:597)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by jfoenixadmin** [comment]
Hello,
Can you please make a pull request?

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
JFXTreeTableRowSkin has been updated so it doesn't use disclosureWidthMap  anymore, feel free to retest using the latest version of JFoenix.

Regards,

**Comment by swftvsn** [comment]
I've now retested this with 1.1.0 and it still happens, even with regular builds (now javafx-gradle-plugin). The JFXTreeTableCellSkin still has the bad code.

**Comment by swftvsn** [comment]
Created pull request in https://github.com/jfoenixadmin/JFoenix/pull/240
