### ISSUE TITLE
jfxSlider.setShowTickLabels(true);  produces  `java.lang.ClassCastException`

### ISSUE THREAD

**Issue by goxr3plus** [jfoenixadmin/JFoenix#243]
Operating System : **Windows 10 X64**
Java Version : **1.8.0_111 x64**
JFoenix Version : **The latest as today [ Now i downloaded it ]** 

---

Trying to user `JFXSlider `method:

`jfxSlider.setShowTickLabels(true);`

-----

I have the following error:

```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.chart.NumberAxis cannot be cast to javafx.scene.layout.StackPane
	at com.jfoenix.skins.JFXSliderSkin.<init>(JFXSliderSkin.java:75)
	at com.jfoenix.controls.JFXSlider.createDefaultSkin(JFXSlider.java:71)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.PaintCollector.liveRepaintRenderJob(PaintCollector.java:320)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:831)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:792)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleViewEvent$368(GlassViewEventHandler.java:871)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleViewEvent(GlassViewEventHandler.java:870)
	at com.sun.glass.ui.View.handleViewEvent(View.java:539)
	at com.sun.glass.ui.View.notifyResize(View.java:875)
	at com.sun.glass.ui.win.WinWindow._setBounds(Native Method)
	at com.sun.glass.ui.Window.setBounds(Window.java:572)
	at com.sun.javafx.tk.quantum.WindowStage.setBounds(WindowStage.java:317)
	at javafx.stage.Window$TKBoundsConfigurator.apply(Window.java:1274)
	at javafx.stage.Window$TKBoundsConfigurator.pulse(Window.java:1290)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:378)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍

**Comment by jfoenixadmin** [comment]
the fix will be pushed to maven by the end of the month, meanwhile you can download the latest version from jfoenix site.

**Comment by goxr3plus** [comment]
Thanks guys . I am using JFoenix in many programs !

Best Regards Alex K.
