### ISSUE TITLE
NullPointerException on checkbox.setSelected in JFXCheckBoxSkin.playSelectAnimation

### ISSUE THREAD

**Issue by arturbosch** [jfoenixadmin/JFoenix#246]
Hi,

I have a simple ListCell implementation in kotlin.
```kotlin
class ListContainerViewCell : ListCell<ObservableTask>() {

	private val doneBox = JFXCheckBox()
	private val description = Label()

	private val root: Parent = gridpane {
		columnConstraints.add(ColumnConstraints().apply { percentWidth = 20.0 })
		columnConstraints.add(ColumnConstraints().apply { percentWidth = 80.0 })
		addColumn(0, doneBox)
		addColumn(1, description)
	}

	override fun updateItem(item: ObservableTask?, empty: Boolean) {
		super.updateItem(item, empty)
		item?.let {
			doneBox.isSelected = it.done
			description.text = it.description
			this.graphic = root
			this.text = null
		}
	}
}
```

When I have more than one item in my initialization list for my list view, I get an NPE in `doneBox.isSelected = it.done`. If I change the JFXCheckBox() to a normal CheckBox everything works as expected.

The Stacktrace is: 

```
java.lang.NullPointerException
	at com.jfoenix.skins.JFXCheckBoxSkin.playSelectAnimation(JFXCheckBoxSkin.java:211)
	at com.jfoenix.skins.JFXCheckBoxSkin.lambda$new$0(JFXCheckBoxSkin.java:109)
	at com.jfoenix.skins.JFXCheckBoxSkin.access$lambda$0(JFXCheckBoxSkin.java)
	at com.jfoenix.skins.JFXCheckBoxSkin$$Lambda$1.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.scene.control.CheckBox.setSelected(CheckBox.java:156)
	at io.gitlab.arturbosch.doable.views.ListContainerViewCell.updateItem(ListContainer.kt:55)
	at io.gitlab.arturbosch.doable.views.ListContainerViewCell.updateItem(ListContainer.kt:40)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:330)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at tornadofx.App.start(App.kt:50)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

Say if you need more information. Btw great project!

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 

Regards,
