### ISSUE TITLE
JFXToolbar crashes (IntelliJ) Scene Builder 2.0

### ISSUE THREAD

**Issue by Baldomo** [jfoenixadmin/JFoenix#252]
As stated in the title, declaring a JFXToolbar in a .fxml file makes Scene Builder crash with AssertionError, however adding the toolbar from the controller class for that fxml does not affect Scene Builder whatsoever. I'm currently using Scene Builder embedded in my IntelliJ IDEA (latest version, 2016.3.4) project window.
As an example:

main_screen.fxml
`<JFXToolbar fx:id="toolbar" prefHeight="40.0" prefWidth="147.0" />`

[Result (Imgur)](http://i.imgur.com/X2aK2wfh.png)

Edit: importing jfoenix jar file in the external Scene Builder and then opening main_screen.fxml works fine.

**Comment by jfoenixadmin** [comment]
Hello,
well it's hard to tell what's causing this issue with the provided info, plz provide more details or some scene builder logs in order to help.

Regards,

**Comment by danielferber** [comment]
Created following fmlx file using IntelliJ (text editor)
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.layout.BorderPane?>
<?import javafx.scene.layout.StackPane?>
<?import com.jfoenix.controls.JFXToolbar?>
<StackPane prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.112" xmlns:fx="http://javafx.com/fxml/1" >
    <BorderPane>
        <top>
            <JFXToolbar/>
        </top>
    </BorderPane>
</StackPane>
```

Then, switching from text editor to the embedded scene builder, I get the message:
Failed to open the file in the Scene Builder
java.lang.AssertionError

From IntelliJ log:
```
2017-04-20 23:42:54,172 [ 741570]   INFO - ceneBuilder.SceneBuilderEditor -  
java.lang.AssertionError
	at com.oracle.javafx.scenebuilder.kit.metadata.klass.ComponentClassMetadata.getSubComponentProperty(ComponentClassMetadata.java:128)
	at com.oracle.javafx.scenebuilder.kit.metadata.klass.ComponentClassMetadata.getSubComponentProperty(ComponentClassMetadata.java:74)
	at com.oracle.javafx.scenebuilder.kit.metadata.util.DesignHierarchyMask.getSubComponentPropertyName(DesignHierarchyMask.java:584)
	at com.oracle.javafx.scenebuilder.kit.metadata.util.DesignHierarchyMask.isAcceptingSubComponent(DesignHierarchyMask.java:501)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.updateTreeItem(AbstractHierarchyPanelController.java:877)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.makeTreeItemBorderPane(AbstractHierarchyPanelController.java:665)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.updateTreeItem(AbstractHierarchyPanelController.java:858)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.makeTreeItem(AbstractHierarchyPanelController.java:647)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.updateTreeItem(AbstractHierarchyPanelController.java:880)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.makeTreeItem(AbstractHierarchyPanelController.java:647)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.updateTreeItems(AbstractHierarchyPanelController.java:734)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.treeview.HierarchyTreeViewController.updatePanel(HierarchyTreeViewController.java:94)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.AbstractHierarchyPanelController.fxomDocumentDidChange(AbstractHierarchyPanelController.java:487)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$60(AbstractPanelController.java:89)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2392)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:664)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl.loadFile(SceneBuilderImpl.java:374)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl.lambda$reload$8(SceneBuilderImpl.java:333)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

I suppose following assertion fails:
```
assert componentClass != javafx.scene.layout.BorderPane.class;
```

**Comment by jfoenixadmin** [comment]
Hello,
@danielferber we were not able to reproduce the issue using the provided example and the latest version of SceneBuilder  8.3.0, can you retest to validate the issue?

Regards,
