### ISSUE TITLE
JFXTreeTableView RecursiveTreeObject incompatible with java.util.Hashmap

### ISSUE THREAD

**Issue by virusavatar** [jfoenixadmin/JFoenix#256]
Issue: When trying to use a hashmap to populate a multi-level JFXTreeTableView, a class cast exception occurs:

```java
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject
	at com.jfoenix.controls.JFXTreeTableView.getTreeItemLevel(JFXTreeTableView.java:136)
	at com.sun.javafx.scene.control.skin.TreeTableCellSkin.leftLabelPadding(TreeTableCellSkin.java:94)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.computePrefHeight(LabeledSkinBase.java:759)
	at javafx.scene.control.Control.computePrefHeight(Control.java:547)
	at javafx.scene.Parent.prefHeight(Parent.java:929)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:587)
	at javafx.scene.control.Control.computePrefHeight(Control.java:547)
	at javafx.scene.Parent.prefHeight(Parent.java:935)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at com.sun.javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1947)
	at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1345)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at IoTBP.Main.start(Main.java:33)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more

```

------------------------------------------------------------------------------------------------------------------

Details: I needed to display several objects of different types from multiple database tables in the same TreeTableView. Because of a lack of documentation, I actively avoided using RecursiveTreeObject and RecursiveTreeItem. Instead, I used a hashmap to circumvent the homogeneous restrictions of java tables.

A compilation error occurs immediately when trying the following declaration:

```java
private JFXTreeTableView<Map<String, Object>> overviewTableView;
```

Error: 
```java
Type parameter 'java.util.Map' is not within its bound; should implement 'com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject<java.util.Map<java.lang.String, java.lang.Object>>'
```

However, this works:

```java
private TreeTableView<Map<String, Object>> overviewTableView;
```

Using this along with the hashmap for a SINGLE-LEVEL tree (root TreeItem with multiple child objects with no children of their own), it is possible to assign the fx:id of the TreeTableView<Map<String, Object>> to a JFXTreeTableView. It will display correctly, as if it were just a normal TableView:

![image](https://cloud.githubusercontent.com/assets/25521934/23683523/68d08a3e-0367-11e7-8c0e-ba0ee6eab3ac.png)

Obviously, this is not useful to display hierarchical data. When manually adding children to any child of the root TreeItem, the class cast exception occurs (as outlined at the top of this post).

This issue does **not** affect javafx.scene.control.TreeTableView. Using a javafx.scene.control.TreeTableView, the hashmap works as expected: 

![image](https://cloud.githubusercontent.com/assets/25521934/23683453/078dbc7e-0367-11e7-8501-80127fc90097.png)

------------------------------------------------------------------------------------------------------------------

Aside from pointing out this issue, I would also like to ask:

1) Why did the JFoenix team decide to use RecursiveTreeObject and RecursiveTreeItem in their implementation of TreeTableView?

2) Is there actual documentation on the proper use of RecursiveTreeObject and RecursiveTreeItem to create multi-level treetables? I have scoured the internet and have not been able to find decent documentation on how these work, which is the sole reason why I had to use hashmaps.

Oh, and thank you for developing  @JFoenix!

Regards

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 
1.  RecursiveTreeObject/RecursiveTreeItem are implemented in order to have tree representation reflected in the data model, and to allow grouping on multiple columns.
2. you can check TreeTableDemo.java for a sample demo.
Mainly RecursiveTreeObject is the data class that you need to extend to have the tree representation in your data model. RecurisveTreeItem is the tree item used to refelect changes from the tree data model to UI and allows multi level grouping.

a fix for you issue has been pushed, however calling the group method might still cause some exceptions.

Regards,
