### ISSUE TITLE
PaswordField : java.lang.RuntimeException: Line.endX : 

### ISSUE THREAD

**Issue by aymen083** [jfoenixadmin/JFoenix#26]
Hi,

I have an exception with JFXPaswordField using validation.
The problem

 JFXTextField don't occur with text field. 

I aligned the implementation of JFXPasswordFieldSkin with the JFXTextFieldSkin and the problem is resolved.

The modified file is in the attachements.
[JFXPasswordFieldSkin.java.txt](https://github.com/jfoenixadmin/JFoenix/files/60551/JFXPasswordFieldSkin.java.txt)

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: Line.endX : A bound value cannot be set.
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:143)
	at javafx.scene.shape.Line.setEndX(Line.java:191)
	at com.jfoenix.skins.JFXPasswordFieldSkin.lambda$layoutChildren$282(JFXPasswordFieldSkin.java:253)
	at com.jfoenix.skins.JFXPasswordFieldSkin.access$lambda$11(JFXPasswordFieldSkin.java)
	at com.jfoenix.skins.JFXPasswordFieldSkin$$Lambda$12.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyDoubleWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyDoubleWrapper.java:177)
	at javafx.beans.property.ReadOnlyDoubleWrapper.fireValueChangedEvent(ReadOnlyDoubleWrapper.java:143)
	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
	at javafx.scene.layout.Region.setWidth(Region.java:858)
	at javafx.scene.layout.Region.resize(Region.java:1364)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2325)
	at javafx.scene.control.SkinBase.layoutInArea(SkinBase.java:702)
	at javafx.scene.control.SkinBase.layoutInArea(SkinBase.java:587)
	at javafx.scene.control.SkinBase.layoutChildren(SkinBase.java:169)
	at com.sun.javafx.scene.control.skin.TextFieldSkin.layoutChildren(TextFieldSkin.java:738)
	at com.jfoenix.skins.JFXPasswordFieldSkin.layoutChildren(JFXPasswordFieldSkin.java:227)
	at javafx.scene.control.Control.layoutChildren(Control.java:576)
	at javafx.scene.Parent.layout(Parent.java:1079)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks

**Comment by jfoenixadmin** [comment]
you are right there are some things that are not modified yet in the JFXPasswordField, however can you send the example that caused the error?

**Comment by jfoenixadmin** [comment]
we added changes to password field, please test again to verify if the issue still persist. thanks
