### ISSUE TITLE
Error al ejecutar demo 

### ISSUE THREAD

**Issue by FlavioRossi** [jfoenixadmin/JFoenix#32]
Error en el demo <IcoMoonFontViewer>

Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.jfoenix.svg.SVGGlyphLoader.loadGlyphsFont(SVGGlyphLoader.java:93)
	at demos.IcoMoonFontViewer.start(IcoMoonFontViewer.java:52)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	... 1 more
Exception running application demos.IcoMoonFontViewer

**Comment by jfoenixadmin** [comment]
couldn't reproduce the error, also please note that IcoMoonFontViewer is a beta demo and will be removed later, the actual demo of the icons viewer is part of the main demo.

**Comment by FlavioRossi** [comment]
Gracias por la respuesta, no había notado que estaba en versión beta. Les agradezco por la librería y las demos están muy bien hechas!...cuando lanzaran la versión terminada?, y quería saber como ver un poco más de documentación con respecto al control de las vistas y otros elementos o si más adelante agregarán más documentación de la librería. Desde ya gracias por todo excelente aporte! Saludos!

**Comment by jfoenixadmin** [comment]
you can check the documentation page on jfoenix site:
http://jfoenix.com/documentation.html#Button

Feel free to contribute to the library :) , Thanks.
