### ISSUE TITLE
"Custom Color" gives exception

### ISSUE THREAD

**Issue by lozohcum** [jfoenixadmin/JFoenix#356]
After clicking "custom color" from JFXColorPicker additional window opens but creates following exception:

> Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.layout.StackPane cannot be cast to javafx.scene.shape.Line
> 	at com.jfoenix.skins.JFXCustomColorPickerDialog.lambda$null$13(JFXCustomColorPickerDialog.java:174)
> 	at com.jfoenix.skins.JFXCustomColorPickerDialog$$Lambda$9.changed(Unknown Source)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
> 	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
> 	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
> 	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
> 	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
> 	at javafx.scene.layout.Region.setBackground(Region.java:617)
> 	at com.jfoenix.skins.JFXCustomColorPickerDialog.lambda$null$21(JFXCustomColorPickerDialog.java:207)
> 	at com.jfoenix.skins.JFXCustomColorPickerDialog$$Lambda$10.run(Unknown Source)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by WaterPlimpie** [comment]
Working fine for me..

**Comment by jfoenixadmin** [comment]
Hello,
can you download the latest JFoenix jar and re-validate the issue, as it's a known issue and already fixed.

Regards,

**Comment by dsendkowski** [comment]
I've checked and it is OK now.

**Comment by lozohcum** [comment]
IT IS NO OK.

Opening "custom color" give this exception:

"C:\Program Files\Java\jdk1.8.0_131\bin\java" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.2\lib\idea_rt.jar=50049:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;D:\lozohcum\IdeaProjects\java_myEvents\out\production\myNotes;D:\lozohcum\IdeaProjects\java_myEvents\material_icons.jar;C:\Users\lozohcum\.m2\repository\mysql\mysql-connector-java\6.0.6\mysql-connector-java-6.0.6.jar;D:\lozohcum\IdeaProjects\java_myEvents\jfoenix.jar" sample.Main jdbc:mysql://sql11.freemysqlhosting.net/sql11182059?user=sql11182059&password=c6IdCiNSrJ
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.layout.StackPane cannot be cast to javafx.scene.shape.Line
	at com.jfoenix.skins.JFXCustomColorPickerDialog.lambda$null$13(JFXCustomColorPickerDialog.java:174)
	at com.jfoenix.skins.JFXCustomColorPickerDialog$$Lambda$9.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
	at javafx.scene.layout.Region.setBackground(Region.java:617)
	at com.jfoenix.skins.JFXCustomColorPickerDialog.lambda$null$21(JFXCustomColorPickerDialog.java:207)
	at com.jfoenix.skins.JFXCustomColorPickerDialog$$Lambda$10.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
