### ISSUE TITLE
Crash on Java 9

### ISSUE THREAD

**Issue by huanghongxun** [jfoenixadmin/JFoenix#365]
Hello! I run JFoenix demo on Java 9 and got this:
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/BooleanConverter
        at com.jfoenix.controls.JFXRippler$StyleableProperties.<clinit>(JFXRippler.java:726)
        at com.jfoenix.controls.JFXRippler.<init>(JFXRippler.java:598)
        at com.jfoenix.controls.JFXRippler.<init>(JFXRippler.java:91)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
        at io.datafx.controller.ViewFactory.createByController(ViewFactory.java:174)
        at io.datafx.controller.flow.FlowHandler.start(FlowHandler.java:146)
        at demos.MainDemo.start(MainDemo.java:41)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.BooleanConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 26 more
Exception running application demos.MainDemo
```
More information: #230 

In Java 9, all com.sun.* classes are inaccessible, and most of them are repackaged, including com.sun.javafx.*
Could you fix it? Even though I guess it is hard to rewrite JFoenix to support Java 9, which is a huge project.

**Comment by jfoenixadmin** [comment]
Hello, 
Well, as mentioned in #230 in java 9 some classes have been refactored however they are still accessible.
the issue is that it will break backward compatibility, thus there will two different jars of JFoenix for Java 8/9.

Regards,

**Comment by huanghongxun** [comment]
Maybe it's unnecessary to make 2 different jars.
See http://openjdk.java.net/jeps/238

**Comment by jfoenixadmin** [comment]
Seems interesting!! will give it a look

Thanks,

**Comment by backtozero** [comment]
@jfoenixadmin Less than a week before Java9.
Please make new branch.

**Comment by TheTrio** [comment]
Is the jar for Java 9 made yet ?

**Comment by TheTrio** [comment]
Java 9 is now released

**Comment by jfoenixadmin** [comment]
Hello, 
Will update JFoenix to be compatible with java 9 as soon as possible.

Regards,

**Comment by syedmohiuddin001** [comment]
i wrote a javafx program 15 time (4 time in java 9 and 8 time in java10 and 3 time in java 8)
for all three version i got 
Exception in Application in start method()?
