### ISSUE TITLE
Can't open the demo with the SceneBuilder

### ISSUE THREAD

**Issue by haljishi** [jfoenixadmin/JFoenix#37]
When I tried  to open main.fxml in the Demo folder with SceneBuilder, I got this error message.
How to fix this issue?

`java.io.IOException: javafx.fxml.LoadException: 
/C:/Users/test/Documents/workspace/JFoenix/demo/resources/fxml/Main.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:92)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:82)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:97)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2384)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:664)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:381)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:549)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:419)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleLaunch(SceneBuilderApp.java:399)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStartGeneric(AppPlatform.java:139)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStart(AppPlatform.java:106)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.start(SceneBuilderApp.java:349)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$55/468253410.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/880504706.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/927958254.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/753051148.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/172623023.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javafx.fxml.LoadException: 
/C:/Users/test/Documents/workspace/JFoenix/demo/resources/fxml/Main.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2605)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2852)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2696)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2665)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2521)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2429)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:89)
	... 25 more
Caused by: java.lang.ClassNotFoundException: de.jensd.fx.fontawesome.AwesomeIcon
de.jensd.fx.fontawesome.AwesomeIcon
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2920)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2909)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2850)
	... 30 more
`

**Comment by jfoenixadmin** [comment]
well, you can't load the Main.fxml directly in scene builder you have to add all the used dependencies in the FXML.

**Comment by haljishi** [comment]
Thanks for your response 
How can I add all the used dependencies to open the file in the scene builder?

**Comment by RAnders00** [comment]
You do it through the (slightly hidden) menu on the library section. Maybe this screenshot will help you?

![scenebuilder_2016-03-01_19-53-48](https://cloud.githubusercontent.com/assets/1629196/13438035/72b23894-dfe7-11e5-86b1-9d919d89ac52.png)

**Comment by diegodesdecolombia** [comment]
Excelente, ¿EL proyecto tiene futuro?

**Comment by RAnders00** [comment]
Please close this
