### ISSUE TITLE
JFXTreeView NullPointerException

### ISSUE THREAD

**Issue by PvdBerg1998** [jfoenixadmin/JFoenix#380]
I have a relatively large data structure bound to a JFXTreeView with JFXTreeCells that display some info.
The TreeView has a vertical scroll bar.

When opening and closing the items in any order, sometimes the animation bugs out and all the items fade out and in (looks really weird). A while after that happened, when opening or closing a node the code crashes with this error:
```
java.lang.NullPointerException
	at com.jfoenix.controls.JFXTreeCell.lambda$new$0(JFXTreeCell.java:73)
	at com.jfoenix.controls.JFXTreeCell$$Lambda$1.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.beans.property.BooleanProperty.setValue(BooleanProperty.java:81)
	at javafx.scene.control.TreeItem.setExpanded(TreeItem.java:522)
	at com.sun.javafx.scene.control.behavior.TreeCellBehavior.handleDisclosureNode(TreeCellBehavior.java:105)
	at com.sun.javafx.scene.control.behavior.CellBehaviorBase.doSelect(CellBehaviorBase.java:199)
	at com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(CellBehaviorBase.java:150)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:95)
...
```

This issue is reproducible but I can't figure out when exactly, I just try spam opening and clicking some nodes.

Please fix this issue asap since I have to fall back to regular JavaFX TreeCells without the fancy animations.

**Comment by PvdBerg1998** [comment]
It appears to happen when the expanded structure is larger than the Region and you scroll down.
When scrolled down, the animation starts being buggy and eventually the crash occurs.

**Comment by jfoenixadmin** [comment]
Hello,

We fixed some issues when dealing with a large data set, hope this will fix the issue you were facing.

Regards,

**Comment by peteryuanpan** [comment]
I've fixed this problem by changing JFXTreeCell to TreeCell, JFXTreeView to TreeView.
Oh my God.

**Comment by jfoenixadmin** [comment]
JFXTreeView animation has been removed, as it was causing many issues in different cases.
