### ISSUE TITLE
PropertyNotFoundException with JFXToggleButton

### ISSUE THREAD

**Issue by ueberhammDesign** [jfoenixadmin/JFoenix#41]
Hello,
I try to use the JFXToggleButton in my application. I build my view inside the JavaFX SceneBuilder and everything looks fine. I customize the colors of the button. When I load the view inside my application, I get the follow exception:
```java
Caused by: javafx.fxml.LoadException: 
unknown path:69

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at de.uni_bremen.roborally.gui.controller.FXMLController.loadFXML(FXMLController.java:158)
	at de.uni_bremen.roborally.gui.controller.FXMLController.afterPropertiesSet(FXMLController.java:73)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 83 more
Caused by: com.sun.javafx.fxml.PropertyNotFoundException: Property "toggleLineColor" does not exist or is read-only.
	at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:348)
	at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325)
	at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
	... 88 more
```

I used try it with the version inside the maven repo and a hand build with the current master. 

The second issue is that the toggle button looks different in my application. The line is thinner and the button text is not showing.

**Comment by jfoenixadmin** [comment]
well, there has been some updates on JFXToggleButton, I believe these changes are not pushed to maven repo yet. in the mean time you can either build jfoenix from github or download jfoenix.jar from JFoenix site using the following <a href="http://jfoenix.com/download/jfoenix.jar">link<a/>

**Comment by jfoenixadmin** [comment]
we pushed the latest version to maven repo, the issue should be fixed.

**Comment by ueberhammDesign** [comment]
Thank you. It works now.
