### ISSUE TITLE
Adding rippler effect to a component gives a null pointer exception

### ISSUE THREAD

**Issue by ramioneclint** [jfoenixadmin/JFoenix#442]
Hi I am trying to add a ripple effect to one of my component:
JFXRippler rippler = new JFXRippler(humanBtn);
borderPane.getChildren().add(rippler); 

However it gives a null pointer exception.

**Comment by ramioneclint** [comment]
Executing C:\Users\HOME\Documents\NetBeansProjects\Registration\dist\run675098530\Registration.jar using platform C:\Program Files\Java\jdk1.8.0_131\jre/bin/java
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javafx.fxml.LoadException: 
file:/C:/Users/HOME/Documents/NetBeansProjects/Registration/dist/run675098530/Registration.jar!/registration/FXMLDocument.fxml

**Comment by jfoenixadmin** [comment]
Hello,
well either your borderPane or humanBtn is null.

Regards,

**Comment by ramioneclint** [comment]
I have the components in Scene builder, I also declared them at the controller.
