### ISSUE TITLE
Using JFXTimePicker caused error java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by CyrilNb** [jfoenixadmin/JFoenix#444]
Hi,

when using JFXTimePicker or JFXDatePicker, an error occured and it seemed to be related to your implementation.

here is an extract of the log: 

```
caused by: java.lang.NoSuchMethodError: com.jfoenix.skins.JFXTimePickerSkin.getEditableInputNode()Ljavafx/scene/control/TextField;
	at com.jfoenix.skins.JFXTimePickerSkin.getDisplayNode(JFXTimePickerSkin.java:186)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.updateDisplayArea(ComboBoxBaseSkin.java:141)
	at com.sun.javafx.scene.control.skin.ComboBoxBaseSkin.computePrefHeight(ComboBoxBaseSkin.java:199)
	at javafx.scene.control.Control.computePrefHeight(Control.java:545)
	at javafx.scene.Parent.prefHeight(Parent.java:918)
```

Can you help me please ?

**Comment by jfoenixadmin** [comment]
Hello,
What java version are you using?

**Comment by CyrilNb** [comment]
1.8

**Comment by jfoenixadmin** [comment]
you need to update the java to at least 1.8.0_60

Regards,
