### ISSUE TITLE
Checkbox doesn't support linear-gradient colors

### ISSUE THREAD

**Issue by LosTigeros** [jfoenixadmin/JFoenix#496]
When I set
`-jfx-checked-color` to `linear-gradient` then it will show me this error:
```
java.lang.ClassCastException: javafx.scene.paint.LinearGradient cannot be cast to javafx.scene.paint.Color
	at com.jfoenix.skins.JFXCheckBoxSkin.createFillTransition(JFXCheckBoxSkin.java:291)
	at com.jfoenix.skins.JFXCheckBoxSkin.<init>(JFXCheckBoxSkin.java:113)
	at com.jfoenix.controls.JFXCheckBox.createDefaultSkin(JFXCheckBox.java:78)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.PaintCollector.liveRepaintRenderJob(PaintCollector.java:320)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:831)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:792)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleViewEvent$368(GlassViewEventHandler.java:871)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleViewEvent(GlassViewEventHandler.java:870)
	at com.sun.glass.ui.View.handleViewEvent(View.java:539)
	at com.sun.glass.ui.View.notifyResize(View.java:875)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinWindow._setResizable(Native Method)
	at com.sun.glass.ui.Window.setResizable(Window.java:649)
	at com.sun.javafx.tk.quantum.WindowStage.setResizable(WindowStage.java:573)
	at javafx.stage.Stage.impl_visibleChanged(Stage.java:1180)
	at javafx.stage.Window$9.invalidated(Window.java:895)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.scene.control.HeavyweightDialog.show(HeavyweightDialog.java:156)
	at javafx.scene.control.Dialog.show(Dialog.java:301)
	at pl.mplauncher.launcher.bootstrap.MPLauncherBootstrap.showError(MPLauncherBootstrap.java:219)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jfoenixadmin** [comment]
Hello,
Well, JFXCheckBoxSkin doesn't support LinearGradient color. it only supports Color for now.

Regards
