### ISSUE TITLE
Please fix/handle JFXSliderSkin NullPointer

### ISSUE THREAD

**Issue by DivineThreepwood** [jfoenixadmin/JFoenix#516]
There is a nullpointers occurring in jfoenix which is not forwarded to the user code.
* This makes it really hard to debug the user code so please catch and handle the nullpointer or forward those to the user code. 

<pre>
WARNING: Exception while evaluating binding
java.lang.NullPointerException
	at com.jfoenix.skins.JFXSliderSkin.lambda$new$0(JFXSliderSkin.java:85)
	at com.jfoenix.skins.JFXSliderSkin$$Lambda$1.call(Unknown Source)
	at javafx.beans.binding.Bindings$6.computeValue(Bindings.java:338)
	at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:153)
	at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:50)
	at javafx.beans.property.ObjectPropertyBase.get(ObjectPropertyBase.java:132)
	at javafx.scene.layout.Region$3.invalidated(Region.java:578)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.access$000(ObjectPropertyBase.java:51)
	at javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:233)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
	at javafx.scene.layout.Region.setBackground(Region.java:617)
	at com.jfoenix.skins.JFXSliderSkin.lambda$initListeners$11(JFXSliderSkin.java:265)
	at com.jfoenix.skins.JFXSliderSkin$$Lambda$12.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
	at javafx.css.StyleableObjectProperty.applyStyle(StyleableObjectProperty.java:68)
	at javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:774)
	at javafx.scene.Node.impl_processCSS(Node.java:9191)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1249)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by jfoenixadmin** [comment]
Hello,
This exception seems related to JFXSlider track background, can you provide more details in order to be able to reproduce the issue?

**Comment by DivineThreepwood** [comment]
Hey, already thanks for the help. 
It seems to be always the same NullPointer so I adjusted the issue description.

Actually I do nothing special with the JFXSlider. I was able to locate the code which is responsible for the Exception to throw but its actually just initialization and adding those as child component.

<pre>
comfortSlider = new JFXSlider(0.0, 100.0, 0.0);
getChildren().addAll(comfortSlider, comfortLabel);
</pre>

to make sure there are no style interferences I tried to reset all style settings of the slider by ``comfortSlider.getStyleClass().clear();`` and actually it works. 

Do you have any idea of further steps?

**Comment by jfoenixadmin** [comment]
Can you provide the css file you are using?

**Comment by DivineThreepwood** [comment]
Here you can find the css file:
https://github.com/openbase/bco.bcozy/blob/master/src/main/resources/css/light.css

I just realized that after calling ``comfortSlider.getStyleClass().clear();`` the JFXSlider is not usable anymore because the handle of the JFXSlider is hided. But this is hopefully not needed anymore after the next jfoenix release. 

Thanks a lot for your support!
