### ISSUE TITLE
Error in css -jfx-label-float: true;

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#554]
Hi, I'm having problems with the tag `-jfx-label-float` in my css, this is my class:
(I'm using the version 1.11.1)
```
.jfx-text-field{
    -jfx-label-float: true;
}
```
And it throws me the following error:
```
java.lang.NullPointerException
	at com.jfoenix.skins.JFXTextFieldSkin.handleControlPropertyChanged(JFXTextFieldSkin.java:322)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.css.StyleableBooleanProperty.set(StyleableBooleanProperty.java:83)
	at javafx.css.StyleableBooleanProperty.applyStyle(StyleableBooleanProperty.java:69)
	at javafx.css.StyleableBooleanProperty.applyStyle(StyleableBooleanProperty.java:45)
	at javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:774)
	at javafx.scene.Node.impl_processCSS(Node.java:9191)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1249)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jfoenixadmin** [comment]
Hello,
I was not able to reproduce the issue, can you provide a simple example demonstrating the issue?
According to the provided exception, it seems that the text value is being set to null instead of empty string. However before fixing it, I'll wait for the example to make sure what the cause is.

Regards,

**Comment by TioCoding** [comment]
Maybe this is the problem, that the initial value is null.
I explain a little. I am using TornadoFx together with JFoenix. And to each JFXTextfield I use the bind property to link it to an object.
I do it this way:

```
(With Kotlin and tornadoFx)
val clienteItem : ClienteItem()

this += JFXTextField().apply{
    promptext = "Name Client"
    bind(itemClient.name)
}

(Only With JavaFx)

private ClienteItem clienteItem;
private JFXTextField txtCliente;
.
..
...
textfield.promptext = "Name Client"
textfield.textProperty().bindBidirectional(clienteItem.name)

```

Maybe when you start the application, the `name` property of my `ClienteItem` is null, so the problem occurs

**Comment by jfoenixadmin** [comment]
I was only able to reproduce when applying the css when the stage is already shown.
@TioCoding can you validate this case?

Regards,
