### ISSUE TITLE
Using gradient on JFXSpinner stroke color causes exception

### ISSUE THREAD

**Issue by gilad4** [jfoenixadmin/JFoenix#564]
Using JFXSpinner with a css such as the following

`.jfx-spinner .arc {
	-fx-stroke: linear-gradient(to top right, red 35%, orange 100%);
}`

 causes class cast excpetion:
```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.paint.LinearGradient cannot be cast to javafx.scene.paint.Color
	at com.jfoenix.skins.JFXSpinnerSkin.createTransition(JFXSpinnerSkin.java:259)
	at com.jfoenix.skins.JFXSpinnerSkin.initialize(JFXSpinnerSkin.java:119)
	at com.jfoenix.skins.JFXSpinnerSkin.layoutChildren(JFXSpinnerSkin.java:229)
	at javafx.scene.control.Control.layoutChildren(Control.java:578)
	...
```

Looking at the source code there is an unnecessary cast to Color and can be simply left as a Paint object

**Comment by jfoenixadmin** [comment]
You are right, thanks for pointing out the issue 👍
