### ISSUE TITLE
Null pointer exception when binding boolean property 

### ISSUE THREAD

**Issue by g9164313** [jfoenixadmin/JFoenix#57]
I get this message as below wehn I call "selectedProperty().bindBidirectional(...)":

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXCheckBoxSkin.lambda$new$179(JFXCheckBoxSkin.java:101)
	at com.jfoenix.skins.JFXCheckBoxSkin.access$lambda$0(JFXCheckBoxSkin.java)
	at com.jfoenix.skins.JFXCheckBoxSkin$$Lambda$1.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)

**Comment by g9164313** [comment]
sorry, I am wrong. I should create a unidirection binding for property

**Comment by jfoenixadmin** [comment]
could not reproduce, make sure you are using the latest version of JFoenix.

**Comment by g9164313** [comment]
You right, I explore the problem again. JFXCheckBox is generated by a table cell factory. The callback of this factory will be invoked twice for the first row item, then the property are also binding twice.

**Comment by dev-seahouse** [comment]
Same here.
`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXCheckBoxSkin.lambda$new$215(JFXCheckBoxSkin.java:101)
	at com.jfoenix.skins.JFXCheckBoxSkin.access$lambda$0(JFXCheckBoxSkin.java)
	at com.jfoenix.skins.JFXCheckBoxSkin$$Lambda$1.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.scene.control.CheckBox.setSelected(CheckBox.java:156)`
