### ISSUE TITLE
Use JFXSnackBar in fxml produces NPE and styleClass does not work

### ISSUE THREAD

**Issue by PeratX** [jfoenixadmin/JFoenix#596]
fxml
`<JFXSnackbar fx:id="snackbar" styleClass="snackbar"/>`
css
```
.snackbar{
    -fx-background-color: #323232;
    -fx-pref-width: 300;
}
```

Produces NPE
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.controls.JFXSnackbar.refreshPopup(JFXSnackbar.java:331)
	at com.jfoenix.controls.JFXSnackbar.lambda$new$2(JFXSnackbar.java:120)
	at com.jfoenix.controls.JFXSnackbar$$Lambda$3.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.Node$LazyBoundsProperty.invalidate(Node.java:9318)
	at javafx.scene.Node.impl_layoutBoundsChanged(Node.java:3403)
	at javafx.scene.Node.impl_notifyLayoutBoundsChanged(Node.java:3816)
	at javafx.scene.Node.impl_geomChanged(Node.java:3767)
	at javafx.scene.Parent.childBoundsChanged(Parent.java:1757)
	at javafx.scene.Node.notifyParentOfBoundsChange(Node.java:3838)
	at javafx.scene.Node.transformedBoundsChanged(Node.java:3800)
	at javafx.scene.Node.localBoundsChanged(Node.java:3782)
	at javafx.scene.Node.impl_geomChanged(Node.java:3768)
	at javafx.scene.Parent.childBoundsChanged(Parent.java:1757)
	at javafx.scene.Node.notifyParentOfBoundsChange(Node.java:3838)
	at javafx.scene.Node.transformedBoundsChanged(Node.java:3800)
	at javafx.scene.Node.localBoundsChanged(Node.java:3782)
	at javafx.scene.Node.impl_geomChanged(Node.java:3768)
	at javafx.scene.Parent.childBoundsChanged(Parent.java:1757)
	at javafx.scene.Node.notifyParentOfBoundsChange(Node.java:3838)
	at javafx.scene.Node.transformedBoundsChanged(Node.java:3800)
	at javafx.scene.Node.localBoundsChanged(Node.java:3782)
	at javafx.scene.Node.impl_geomChanged(Node.java:3768)
	at javafx.scene.Parent.childBoundsChanged(Parent.java:1757)
	at javafx.scene.Node.notifyParentOfBoundsChange(Node.java:3838)
	at javafx.scene.Node.transformedBoundsChanged(Node.java:3800)
	at javafx.scene.Node.localBoundsChanged(Node.java:3782)
	at javafx.scene.Node.impl_geomChanged(Node.java:3768)
	at javafx.scene.text.Text.impl_geomChanged(Text.java:766)
	at javafx.scene.text.Text$8.invalidated(Text.java:751)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
	at javafx.css.StyleableObjectProperty.applyStyle(StyleableObjectProperty.java:68)
	at javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:774)
	at javafx.scene.Node.impl_processCSS(Node.java:9191)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:875)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at javafx.stage.Stage.show(Stage.java:259)
	at fun.pixiv.pandesktop.Pan.start(Pan.java:64) which is primaryStage.show();
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```
Java
```
FXMLLoader fxmlLoader = new FXMLLoader(Pan.class.getClassLoader() .getResource("fxml/main.fxml"));
            Parent root = fxmlLoader.load();
            controller = fxmlLoader.getController();
            controller.init();
            primaryStage.setTitle(NAME);
            Scene scene = new Scene(root, 800, 600);
            final ObservableList<String> stylesheets = scene.getStylesheets();
            stylesheets.addAll(Pan.class.getResource("/css/jfoenix-fonts.css").toExternalForm(),
                    Pan.class.getResource("/css/jfoenix-design.css").toExternalForm(),
                    Pan.class.getResource("/css/main.css").toExternalForm());
            primaryStage.setScene(scene);
            primaryStage.show();
```

OracleJDK 8u162
JFoenix 8.0.1 from maven central
Windows 10 1709

Please help! Thanks

**Comment by Gabirel** [comment]
I have the same issue. Could you please tell me how to solve this?  Thanks

**Comment by PeratX** [comment]
```java
        snackbar = new JFXSnackbar(root);
        snackbar.setPrefWidth(400);
```

**Comment by Gabirel** [comment]
So, the only way to use snackbar is in code instead of in FXML? right?

**Comment by PeratX** [comment]
YES. IT IS THE ONLY WAY.

**Comment by Gabirel** [comment]
Okay. Thanks for your replying
