### ISSUE TITLE
Did not show virtual keyboard for edit JFXTextField

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#666]
Hello,
After change version JFoenix to 8.0.2, I had problem with show virtual keyboard of Android. I used jfxmobile-plugin 1.3.10.

**Comment by jfoenixadmin** [comment]
Hello,
can you provide more details about the issue? is there any exception in the log file? did you try using an older/latest version of JFoenix ?

**Comment by svininykh** [comment]
I used version 8.0.3. Exception from log:
```
E/javafx.scene.control(27197): Failed to load skin 'com.jfoenix.android.skins.JFXTextFieldSkinAndroid' for control JFXTextField@2b50c37c[styleClass=text-input text-field jfx-text-field]
E/javafx.scene.control(27197): java.lang.ClassNotFoundException: com.jfoenix.android.skins.JFXTextFieldSkinAndroid
E/javafx.scene.control(27197): 	at java.lang.Class.classForName(Native Method)
E/javafx.scene.control(27197): 	at java.lang.Class.forName(Class.java:309)
E/javafx.scene.control(27197): 	at java.lang.Class.forName(Class.java:273)
E/javafx.scene.control(27197): 	at javafx.scene.control.Control.loadClass(Control.java:111)
E/javafx.scene.control(27197): 	at javafx.scene.control.Control.loadSkinClass(Control.java:698)
E/javafx.scene.control(27197): 	at javafx.scene.control.Control$4.invalidated(Control.java:658)
E/javafx.scene.control(27197): 	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
E/javafx.scene.control(27197): 	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
E/javafx.scene.control(27197): 	at javafx.css.StyleableStringProperty.set(StyleableStringProperty.java:83)
E/javafx.scene.control(27197): 	at javafx.scene.control.Control$4.set(Control.java:650)
E/javafx.scene.control(27197): 	at javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:69)
E/javafx.scene.control(27197): 	at javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:45)
E/javafx.scene.control(27197): 	at javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:774)
E/javafx.scene.control(27197): 	at javafx.scene.Node.impl_processCSS(Node.java:9189)
E/javafx.scene.control(27197): 	at javafx.scene.Parent.impl_processCSS(Parent.java:1241)
E/javafx.scene.control(27197): 	at javafx.scene.control.Control.impl_processCSS(Control.java:861)
E/javafx.scene.control(27197): 	at javafx.scene.Parent.impl_processCSS(Parent.java:1272)
E/javafx.scene.control(27197): 	at javafx.scene.Node.processCSS(Node.java:9056)
E/javafx.scene.control(27197): 	at javafx.scene.Scene.doCSSPass(Scene.java:545)
E/javafx.scene.control(27197): 	at javafx.scene.Scene.preferredSize(Scene.java:1643)
E/javafx.scene.control(27197): 	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
E/javafx.scene.control(27197): 	at javafx.stage.Window$9.invalidated(Window.java:846)
E/javafx.scene.control(27197): 	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
E/javafx.scene.control(27197): 	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
E/javafx.scene.control(27197): 	at javafx.stage.Window.setShowing(Window.java:922)
E/javafx.scene.control(27197): 	at javafx.stage.Window.show(Window.java:937)
E/javafx.scene.control(27197): 	at javafx.stage.Stage.show(Stage.java:259)
E/javafx.scene.control(27197): 	at mobi.nordpos.jfoenix.MainApp.start(MainApp.java:30)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$145(LauncherImpl.java:863)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.LauncherImpl.access$lambda$8(LauncherImpl.java)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.LauncherImpl$$Lambda$9.run(Unknown Source)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$158(PlatformImpl.java:326)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.access$lambda$6(PlatformImpl.java)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl$$Lambda$7.run(Unknown Source)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.lambda$null$156(PlatformImpl.java:295)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.access$lambda$18(PlatformImpl.java)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl$$Lambda$19.run(Unknown Source)
E/javafx.scene.control(27197): 	at java.security.AccessController.doPrivileged(AccessController.java:52)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$157(PlatformImpl.java:294)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl.access$lambda$5(PlatformImpl.java)
E/javafx.scene.control(27197): 	at com.sun.javafx.application.PlatformImpl$$Lambda$6.run(Unknown Source)
E/javafx.scene.control(27197): 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
E/javafx.scene.control(27197): 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:52)
E/javafx.scene.control(27197): 	at java.lang.Thread.run(Thread.java:818)
E/javafx.scene.control(27197): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jfoenix.android.skins.JFXTextFieldSkinAndroid" on path: DexPathList[[zip file "/data/app/mobi.nordpos.jfoenix-1/base.apk"],nativeLibraryDirectories=[/data/app/mobi.nordpos.jfoenix-1/lib/arm, /vendor/lib, /system/lib]]
E/javafx.scene.control(27197): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/javafx.scene.control(27197): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/javafx.scene.control(27197): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/javafx.scene.control(27197): 	... 44 more
E/javafx.scene.control(27197): 	Suppressed: java.lang.ClassNotFoundException: com.jfoenix.android.skins.JFXTextFieldSkinAndroid
E/javafx.scene.control(27197): 		at java.lang.Class.classForName(Native Method)
E/javafx.scene.control(27197): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/javafx.scene.control(27197): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/javafx.scene.control(27197): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/javafx.scene.control(27197): 		... 45 more
```

**Comment by jfoenixadmin** [comment]
yes the retro-lambda build is for mobile.
Regards,
