### ISSUE TITLE
 Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.jfoenix.controls.events.JFXAutoCompleteEvent

### ISSUE THREAD

**Issue by XlintXms** [jfoenixadmin/JFoenix#702]
I have this code : 
`  JFXAutoCompletePopup<String> autoCompletePopup = new JFXAutoCompletePopup<>();        
        autoCompletePopup.getSuggestions().addAll("Fruit", "Fruits", "Frites", "Cheese!");
        autoCompletePopup.setSelectionHandler(event -> {
            textField.setText(event.getObject());
        });
        textField.textProperty().addListener(observable -> {
            //The filter method uses the Predicate to filter the Suggestions defined above
            //I choose to use the contains method while ignoring cases
            autoCompletePopup.filter(item -> item.toLowerCase().contains(textField.getText().toLowerCase()));
            //Hide the autocomplete popup if the filtered suggestions is empty or when the box's original popup is open
            if (autoCompletePopup.getFilteredSuggestions().isEmpty()) {
                autoCompletePopup.hide();
            } else {
                autoCompletePopup.show(textField);
            }
        });
       `

When I run this piece of code it invokes this exception : 
`
	at com.jfoenix.skins.JFXAutoCompletePopupSkin.selectItem(JFXAutoCompletePopupSkin.java:139)
	at com.jfoenix.skins.JFXAutoCompletePopupSkin.lambda$registerEventListener$1(JFXAutoCompletePopupSkin.java:71)
	at com.jfoenix.skins.JFXAutoCompletePopupSkin$$Lambda$2.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$355(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: EventType "DIALOG_CLOSED"with parent "EVENT" already exists
	at javafx.event.EventType.register(EventType.java:186)
	at javafx.event.EventType.<init>(EventType.java:128)
	at com.jfoenix.controls.events.JFXAutoCompleteEvent.<clinit>(JFXAutoCompleteEvent.java:44)
	... 33 more
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.jfoenix.controls.events.JFXAutoCompleteEvent`

I used CustomTextField from ControlFX  in JFXDialog.

**Comment by jfoenixadmin** [comment]
Which JFoenix version are you using?

**Comment by jfoenixadmin** [comment]
will close this issue since @XlintXms didn't reply, and most probably this is related to using wrong JFoenix version.
