### ISSUE TITLE
JFXDrawersStack error during toggle on Android 5.1.1

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#755]
Hello,

I had a problem toggle with JFXDrawersStack. JFoenix version 8.0.4.lambda Log:

```
E/AndroidRuntime(20574): FATAL EXCEPTION: JavaFX Application Thread
E/AndroidRuntime(20574): Process: mobi.nordpos.appkkm, PID: 20574
E/AndroidRuntime(20574): java.lang.NoSuchMethodError: No virtual method forEach(Ljava/util/function/BiConsumer;)V in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(20574): 	at com.jfoenix.controls.JFXDrawer.open(JFXDrawer.java:546)
E/AndroidRuntime(20574): 	at com.jfoenix.controls.JFXDrawersStack.toggle(JFXDrawersStack.java:178)
E/AndroidRuntime(20574): 	at mobi.nordpos.appkkm.ui.MenuUserInterface.lambda$new$5(MenuUserInterface.java:127)
E/AndroidRuntime(20574): 	at mobi.nordpos.appkkm.ui.MenuUserInterface$$Lambda$5.handle(Unknown Source)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
E/AndroidRuntime(20574): 	at javafx.event.Event.fireEvent(Event.java:198)
E/AndroidRuntime(20574): 	at javafx.scene.Node.fireEvent(Node.java:8411)
E/AndroidRuntime(20574): 	at javafx.scene.control.Button.fire(Button.java:185)
E/AndroidRuntime(20574): 	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
E/AndroidRuntime(20574): 	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
E/AndroidRuntime(20574): 	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
E/AndroidRuntime(20574): 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
E/AndroidRuntime(20574): 	at javafx.event.Event.fireEvent(Event.java:198)
E/AndroidRuntime(20574): 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3761)
E/AndroidRuntime(20574): 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3489)
E/AndroidRuntime(20574): 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
E/AndroidRuntime(20574): 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2498)
E/AndroidRuntime(20574): 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
E/AndroidRuntime(20574): 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
E/AndroidRuntime(20574): 	at java.security.AccessController.doPrivileged(AccessController.java:52)
E/AndroidRuntime(20574): 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$335(GlassViewEventHandler.java:388)
E/AndroidRuntime(20574): 	at com.sun.java
```

**Comment by svininykh** [comment]
Problem only in version 8.0.4

**Comment by jfoenixadmin** [comment]
@svininykh thanks for pointing out the issue 👍 . The fix will be included in the next release.
Regards,
