### ISSUE TITLE
Problem with jar file exported from a javafx project (with jfoeniX inported) 

### ISSUE THREAD

**Issue by williamlatt** [jfoenixadmin/JFoenix#757]
Hi guys, 
when I export my JavaFX project into an executable jar after I cant start my file. I got this error from cmd:

java.lang.NullPointerException: Location is required.
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
        at application.Main.start(Main.java:19)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

PS: From Eclipse everything works perfectly! only the jar give those errors. 
I search a lot on internet but I couldn't find a solution. 
PS2: I asked here because if I export a text project with only basics JavaFX element all run without problem even the jar file.
can someone help me pls?

**Comment by skmedix** [comment]
Make sure your FXMLLoader does have the correct path to fxml file that you're trying to load.

**Comment by jfoenixadmin** [comment]
This issue is related to your FXML path in your project and how you are accessing them, Will close this issue as it's not related to JFoenix.

Regards,
