### ISSUE TITLE
JFXDatePicker ClassCastException

### ISSUE THREAD

**Issue by mohlek** [jfoenixadmin/JFoenix#759]
Version: 8.0.1

When extending JFXDatePicker, java produces the following exception:

```java
public class CustomDateField extends JFXDatePicker {

    public CustomDateField() {
    }
}
```

```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: com.sun.javafx.scene.control.skin.ComboBoxPopupControl$FakeFocusTextField cannot be cast to com.jfoenix.controls.JFXTextField
    at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:107)
    at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:103)
    at javafx.scene.control.Control.impl_processCSS(Control.java:872)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
    at javafx.scene.Node.processCSS(Node.java:9058)
    at javafx.scene.Scene.doCSSPass(Scene.java:545)
    at javafx.scene.Scene.access$3600(Scene.java:159)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:748)
```

I'd like to customize the JFXDatePicker but its not possible.

**Comment by mohlek** [comment]
doesn't work with 8.0.4 either.

**Comment by jfoenixadmin** [comment]
I see, thanks for pointing out the issue 👍. the fix will be included in the next release.
Regards,

**Comment by mohlek** [comment]
thanks for the fast response. when will be the next scheduled release?

**Comment by jfoenixadmin** [comment]
Hopefully by the end of this month
