### ISSUE TITLE
No interface method forEach remove from ObservableList 

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#770]
I used ObservableList for created TreeItem of JFXTreeTableView. But during remove item from ObservableList Android 5.1.1 application throw "No interface method forEach" error. Please, help me resolve this problem.

**Comment by svininykh** [comment]
This problem repeated for clear function.

```
E/AndroidRuntime(25069): java.lang.NoSuchMethodError: No interface method forEach(Ljava/util/function/Consumer;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(25069): 	at com.jfoenix.controls.RecursiveTreeItem.lambda$addChildrenListener$8(RecursiveTreeItem.java:198)
E/AndroidRuntime(25069): 	at com.jfoenix.controls.RecursiveTreeItem$$Lambda$7.onChanged(Unknown Source)
E/AndroidRuntime(25069): 	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:163)
E/AndroidRuntime(25069): 	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:72)
E/AndroidRuntime(25069): 	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:232)
E/AndroidRuntime(25069): 	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
E/AndroidRuntime(25069): 	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
E/AndroidRuntime(25069): 	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:204)
E/AndroidRuntime(25069): 	at com.sun.javafx.collections.ObservableListWrapper.clear(ObservableListWrapper.java:157)
E/AndroidRuntime(25069): 	at mobi.nordpos.appkkm.ui.settings.CaptionsPanel.lambda$new$5(CaptionsPanel.java:171)
E/AndroidRuntime(25069): 	at mobi.nordpos.appkkm.ui.settings.CaptionsPanel$$Lambda$4.handle(Unknown Source)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
E/AndroidRuntime(25069): 	at javafx.event.Event.fireEvent(Event.java:198)
E/AndroidRuntime(25069): 	at javafx.scene.Node.fireEvent(Node.java:8411)
E/AndroidRuntime(25069): 	at javafx.scene.control.Button.fire(Button.java:185)
E/AndroidRuntime(25069): 	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
E/AndroidRuntime(25069): 	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
E/AndroidRuntime(25069): 	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
E/AndroidRuntime(25069): 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
E/AndroidRuntime(25069): 	at javafx.event.Event.fireEvent(Event.java:198)
E/AndroidRuntime(25069): 	at javafx.sce
```
