### ISSUE TITLE
Adding ScrollPane to JFXPopup

### ISSUE THREAD

**Issue by OguzcanKarakoc** [jfoenixadmin/JFoenix#778]
When adding a ScrollPane in a JFXPopup it returns a `NullPinterException`. I've made a demo so you can simply see what it looks like and test it out yourself:

**Main**

```
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXPopup;
import com.jfoenix.controls.JFXTextField;
import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class Main extends Application {

  public static void main(String[] args) {
    launch();
  }

  private JFXPopup popup;

  @Override
  public void start(Stage primaryStage) throws Exception {
    primaryStage.setMinWidth(400);
    primaryStage.setMinHeight(400);

    Parent root = new StackPane();

    Button button = new Button("Test scrollbar-bug");

    button.setOnAction(event -> {
      popup = new JFXPopup();

      ScrollPane scrollPane = new ScrollPane();
      scrollPane.setContent(generateForm());

      System.out.println("ScrollPane: " + scrollPane);
      System.out.println("ScrollPane content: " + scrollPane.getContent());
      System.out.println("Popup content before adding anything: " + popup.getPopupContent());

      popup.setPopupContent(scrollPane);

      System.out.println("Popup content after ading the ScrollPane: " + popup.getPopupContent());

      popup.show(root);
    });

    ((StackPane) root).getChildren().add(button);

    Scene scene = new Scene(root);

    primaryStage.setScene(scene);
    primaryStage.show();
  }

  private Parent generateForm() {

    VBox vBox = new VBox();
    vBox.setAlignment(Pos.TOP_CENTER);
    vBox.setFillWidth(true);

    Label label = new Label("Edit Leaf");
    JFXTextField textField = new JFXTextField("Test field name");
    JFXButton connectButton = new JFXButton("Test button name");

    vBox.getChildren().addAll(label,textField,connectButton);
    return vBox;
  }

}
```
**The exception** 

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.scrollBoundsIntoView(ScrollPaneSkin.java:985)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.lambda$initialize$12(ScrollPaneSkin.java:632)
	at javafx.graphics/com.sun.javafx.scene.traversal.TraversalEngine.notifyTraversedTo(TraversalEngine.java:91)
	at javafx.graphics/com.sun.javafx.scene.traversal.TopMostTraversalEngine.notifyTreeTraversedTo(TopMostTraversalEngine.java:119)
	at javafx.graphics/com.sun.javafx.scene.traversal.TopMostTraversalEngine.focusAndNotify(TopMostTraversalEngine.java:111)
	at javafx.graphics/com.sun.javafx.scene.traversal.TopMostTraversalEngine.traverseToFirst(TopMostTraversalEngine.java:132)
	at javafx.graphics/javafx.scene.Scene.focusInitial(Scene.java:2126)
	at javafx.graphics/javafx.scene.Scene.access$3100(Scene.java:173)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.focusCleanup(Scene.java:2466)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2487)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

And finally the results that are printed with `System.out.println` 

```
ScrollPane: ScrollPane@5302efa5[styleClass=scroll-pane]
ScrollPane content: VBox@208c10bf
Popup content before adding anything: null
Popup content after ading the ScrollPane: ScrollPane@5302efa5[styleClass=scroll-pane]
```

As you can see the `System.out.println` shows the expected result, so where does the NullPointerException come from?

**Comment by jfoenixadmin** [comment]
Hello,
Well the problem lies in `popup.show(root);` this is unexpected issue, will look into it. 
Thanks @OguzcanKarakoc for pointing out the issue 👍 

Regards,

**Comment by OguzcanKarakoc** [comment]
I'm wondering when this change will be put in the maven repository. Or in the download links. version 9.0.6 doesn't seem to have this fixed.

**Comment by jfoenixadmin** [comment]
it will be included in the next version *.*.8 tomorrow
