### ISSUE TITLE
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException

### ISSUE THREAD

**Issue by javabootstar** [jfoenixadmin/JFoenix#789]
I run this Project, I'm getting NullPointerException

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.javabootstar.grofers.model.NGrofersApplicationFxController$1.run(NGrofersApplicationFxController.java:169)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```
```

**Comment by javabootstar** [comment]
i'm set the value of JFXComboBox when I'm  getting runtime Exception.Why..? Please Help

**Comment by javabootstar** [comment]
![nullpointerexception](https://user-images.githubusercontent.com/12372419/43025017-cb9e4074-8c8d-11e8-8d0a-94c1eb593af7.PNG)

**Comment by javabootstar** [comment]
https://stackoverflow.com/questions/51450229/fxml-setting-getting-the-value-jfxcombbox-throws-nullpointerexception

**Comment by jfoenixadmin** [comment]
Well, according to the exception. it seems that cdSelectProduct combobox is null.
will close this issue as it's not related to JFoenix development.

Regards,
