### ISSUE TITLE
JFXTextField Error When Clicked

### ISSUE THREAD

**Issue by LandyLane** [jfoenixadmin/JFoenix#791]
Made a new GUI using JFoenix 8.0.5. Having a blank Controller  (from scenebuilder) and clicking on the JFXTextField will produce the following error in the console:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.jfoenix.skins.JFXTextAreaSkin.lambda$new$4(JFXTextAreaSkin.java:111)
	at com.jfoenix.skins.JFXTextAreaSkin$$Lambda$6.get(Unknown Source)
	at com.jfoenix.transitions.JFXKeyValue.getEndValue(JFXKeyValue.java:50)
	at com.jfoenix.transitions.JFXAnimationTimer$AnimationHandler.animate(JFXAnimationTimer.java:239)
	at com.jfoenix.transitions.JFXAnimationTimer.handle(JFXAnimationTimer.java:100)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$485(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```

[Link to view error during usage](https://i.gyazo.com/7bbf23e117039f1293414e6dd4c1cf0d.mp4)

**Comment by LandyLane** [comment]
Update: Switching to JFoenix 8.0.4 fixed this issue.

**Comment by jfoenixadmin** [comment]
can you attach the fxml file?

**Comment by Dearbone** [comment]
Because the latest response was already 7 days ago, i wanted to response too.
I can confirm the mentioned behavior for the JFXTextArea control.

`<JFXTextArea fx:id="taComment" minHeight="30" prefHeight="60" disable="true"> 
					<padding>
						<Insets top="10" left="10" right="10" bottom="10"/> 
					</padding>
				</JFXTextArea>`

There is nothing special with the JFXTextArea.
If I click into it, it will throw following exception until the JFXTextArea loses focus:

`java.lang.NullPointerException
at com.jfoenix.skins.JFXTextAreaSkin.lambda$new$4(JFXTextAreaSkin.java:111)
at com.jfoenix.skins.JFXTextAreaSkin$$Lambda$6.get(Unknown Source)
at com.jfoenix.transitions.JFXKeyValue.getEndValue(JFXKeyValue.java:50)
at com.jfoenix.transitions.JFXAnimationTimer$AnimationHandler.animate(JFXAnimationTimer.java:239)
at com.jfoenix.transitions.JFXAnimationTimer.handle(JFXAnimationTimer.java:100)
at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$485(AnimationTimer.java:57)
at java.security.AccessController.doPrivileged(Native Method)
at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
at java.lang.Thread.run(Unknown Source)`

I hope the short fxml is enough

**Comment by jfoenixadmin** [comment]
I see, thanks for pointing out the issue 👍 . In the new version 8.0.6, all Input controls have been refactored to use the same code for label float property / validations. Thus no more similar bugs :)

Regards,
