### ISSUE TITLE
RecursiveTreeItem(Callback<RecursiveTreeObject<T>, ObservableList<T>> func) causes NPE

### ISSUE THREAD

**Issue by micheljung** [jfoenixadmin/JFoenix#807]
```
new RecursiveTreeItem(param -> FXCollections.emptyObservableList())
```

```
Caused by: java.lang.NullPointerException
	at com.jfoenix.controls.RecursiveTreeItem.init(RecursiveTreeItem.java:161)
	at com.jfoenix.controls.RecursiveTreeItem.<init>(RecursiveTreeItem.java:107)
	at com.jfoenix.controls.RecursiveTreeItem.<init>(RecursiveTreeItem.java:84)
```

Because the constructor sets `value` to null, `addChildrenListener` isn't called causing `filteredItems` to not be initialized, resulting in the NPE.

**Comment by jfoenixadmin** [comment]
Thanks @micheljung for pointing out the issue 👍
