### ISSUE TITLE
JavaFX11 Modules & Jfoenix

### ISSUE THREAD

**Issue by juzimmer** [jfoenixadmin/JFoenix#862]
Trying to modularize my javafx 10 application to 11and I start getting these errors when my application tries to load certain elements like the TabPane.

`Caused by: java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module com.jfoenix`

**Comment by jfoenixadmin** [comment]
you need to add the proper export to your project when running / compiling. as most of internal JavaFX api is no longer accessible directly.

**Comment by Alraku** [comment]
Hey, have you figured out what export should be? I have the same problem but with javafx.graphics library

**Comment by juzimmer** [comment]
> 
> 
> Hey, have you figured out what export should be? I have the same problem but with javafx.graphics library

I was able to fix all my exports by reading the errors from stack trace. MY SOLUTION for the views that I used in my project are as follows : 

[StackOverflow](https://stackoverflow.com/questions/53037442/how-to-fix-jfoenix-modules-with-javafx-11)

--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix

**Comment by Alraku** [comment]
Thank you for your resposnse, I assume you have added these statements in VM options right? I ask about it because in my project there is a module-info.java file and everything what is needed I just write there as a "requires" or "exports".

**Comment by juzimmer** [comment]
> 
> 
> Thank you for your resposnse, I assume you have added these statements in VM options right? I ask about it because in my project there is a module-info.java file and everything what is needed I just write there as a "requires" or "exports".

As to my understanding... add my above text to VM options and just have your base requires in your module info. IntelliJ does a good job of telling you which requires are missing from your module info based on your imported libraries in use by your project. Just rebuild your project and alt enter on any errors for your imports in the namespaces and it should give you option to add the required exports to the module info file.

**Comment by badcannon** [comment]
Hey there any idea how can add the vm settings to my maven project ?

**Comment by dbvgonezoren** [comment]
> Hey there any idea how I can add the vm settings to my maven project ?

Same question

**Comment by yashp1196** [comment]
I am running on Intellij IDE, and  I am also stuck as well. Tried everything that is commanded above. Please help as, if any one have succeeded then please show as how to fix the problem. 

//
Caused by: java.lang.IllegalAccessError: class com.jfoenix.skins.JFXTabPaneSkin (in unnamed module @0x60c5d139) cannot access class com.sun.javafx.scene.control.behavior.TabPaneBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x60c5d139

Please help me!!

**Comment by jesa29** [comment]
> > Hey there any idea how I can add the vm settings to my maven project ?
> 
> Same question

Here we go
```
<plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.3</version>
                <configuration>
                    <options>
                        <option>--add-opens</option>
                        <option>javafx.graphics/javafx.css=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.base/com.sun.javafx.runtime=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.base/com.sun.javafx.binding=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.base/com.sun.javafx.event=ALL-UNNAMED</option>
                        <option>--add-opens</option>
                        <option>javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED</option>
                        <option>--add-exports</option>
                        <option>javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix</option>
                        <option>--add-exports</option>
                        <option>javafx.controls/com.sun.javafx.scene.control=com.jfoenix</option>
                        <option>--add-exports</option>
                        <option>javafx.base/com.sun.javafx.binding=com.jfoenix</option>
                        <option>--add-exports</option>
                        <option>javafx.graphics/com.sun.javafx.stage=com.jfoenix</option>
                        <option>--add-exports</option>
                        <option>javafx.base/com.sun.javafx.event=com.jfoenix</option>
                    </options>
                    <mainClass>application.Main</mainClass>
                </configuration>
            </plugin>
```

**Comment by MovinduLochana** [comment]
**I'm still getting this error**


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/C:/Users/Lochana/.m2/repository/com/jfoenix/jfoenix/9.0.10/jfoenix-9.0.10.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)
WARNING: Please consider reporting this to the maintainers of com.jfoenix.adapters.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x567ca99b) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x567ca99b
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.jfoenix.skins.JFXGenericPickerSkin.<init>(JFXGenericPickerSkin.java:62)
	at com.jfoenix.skins.JFXDatePickerSkin.<init>(JFXDatePickerSkin.java:60)
	at com.jfoenix.controls.JFXDatePicker.createDefaultSkin(JFXDatePicker.java:100)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1399)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9540)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1745)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at com.mycompany.javafxapp/com.mycompany.javafxapp.App.start(App.java:22)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Exception running application com.mycompany.javafxapp.App
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:504)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:394)
    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:100)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:504)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:394)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:100)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  8.423 s
Finished at: 2020-08-06T13:27:51+05:30
------------------------------------------------------------------------
Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.4:run (default-cli) on project javaFXApp: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by jesa29** [comment]
@MovinduLochana since my last comment I've added some changes in my own project, you can try to check it, but the best way is to understand how modules work, this helped me to fix issues in my project

```
--module-path
D:\Java\javafx-sdk-11.0.2\lib
--add-modules
javafx.base,javafx.controls,javafx.fxml,javafx.graphics
--add-opens
javafx.graphics/javafx.css=ALL-UNNAMED
--add-opens
javafx.base/com.sun.javafx.runtime=ALL-UNNAMED
--add-opens
javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED
--add-opens
javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED
--add-opens
javafx.base/com.sun.javafx.binding=ALL-UNNAMED
--add-opens
javafx.base/com.sun.javafx.event=ALL-UNNAMED
--add-opens
javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
--add-opens
javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
--add-exports
javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports
javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports
javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports
javafx.base/com.sun.javafx.event=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.scene=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.scene.text=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.geom=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.util=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.scene.traversal=com.jfoenix
```

**Comment by MovinduLochana** [comment]
> @MovinduLochana since my last comment I've added some changes in my own project, you can try to check it, but the best way is to understand how modules work, this helped me to fix issues in my project
> 
> ```
> --module-path
> D:\Java\javafx-sdk-11.0.2\lib
> --add-modules
> javafx.base,javafx.controls,javafx.fxml,javafx.graphics
> --add-opens
> javafx.graphics/javafx.css=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.runtime=ALL-UNNAMED
> --add-opens
> javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED
> --add-opens
> javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.binding=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.event=ALL-UNNAMED
> --add-opens
> javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
> --add-opens
> javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
> --add-exports
> javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
> --add-exports
> javafx.controls/com.sun.javafx.scene.control=com.jfoenix
> --add-exports
> javafx.base/com.sun.javafx.binding=com.jfoenix
> --add-exports
> javafx.base/com.sun.javafx.event=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.stage=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene.text=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.geom=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.util=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene.traversal=com.jfoenix
> ```

thank you very much brother, while(true) {thank you bro!}

**Comment by castillo0o9** [comment]
in my case using Netbeans 12.0, JavaFX 11, OpenJDK 11 and JFoenix 9.0.10
I got rid of the following errors by:

1. Disabling _Compile on Save_ on the **Project Properties** -> **Compiling**
2. Adding on the VM options under **Run** using
`--module-path "C:\Program Files\Java\javafx-sdk-11.0.2\lib" --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics --add-opens javafx.graphics/javafx.css=ALL-UNNAMED --add-opens javafx.base/com.sun.javafx.runtime=ALL-UNNAMED --add-opens javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED --add-opens javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED --add-opens javafx.base/com.sun.javafx.binding=ALL-UNNAMED --add-opens javafx.base/com.sun.javafx.event=ALL-UNNAMED --add-opens javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED --add-opens javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED --illegal-access=warn`

IntelliJ IDEA 2020.2.1, JavaFX 11, OpenJDK 11 and JFoenix 9.0.10
VM options
```
--module-path
"C:\Program Files\Java\javafx-sdk-11.0.2\lib"
--add-modules
javafx.controls,javafx.fxml
--add-modules=javafx.base
--add-modules=javafx.controls
--add-modules=javafx.fxml
--add-modules=javafx.graphics
--add-modules=javafx.media
--add-modules=javafx.swing
--add-modules=javafx.web
--add-opens
javafx.base/com.sun.javafx.runtime=ALL-UNNAMED
--add-opens
javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED
--add-opens
javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED
--add-opens
javafx.base/com.sun.javafx.binding=ALL-UNNAMED
--add-opens
javafx.base/com.sun.javafx.event=ALL-UNNAMED
--add-opens
javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
--illegal-access=warn
```

  **NOTE:**
1. Consider using space instead of new line on the VM options in Netbeans
2. After this, the only error/warning I got so far was:
`WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/path/jfoenix-9.0.10.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)`
but I was able to run and modify my project

**Comment by rawnl** [comment]
Hi guys, I'am having the ssame probleme with JFXDatePickrer. I'm using Java 13, JFoenix 9 in Eclipse. Can someone help me to fix it ?

**Comment by Nasroo** [comment]
> @MovinduLochana since my last comment I've added some changes in my own project, you can try to check it, but the best way is to understand how modules work, this helped me to fix issues in my project
> 
> ```
> --module-path
> D:\Java\javafx-sdk-11.0.2\lib
> --add-modules
> javafx.base,javafx.controls,javafx.fxml,javafx.graphics
> --add-opens
> javafx.graphics/javafx.css=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.runtime=ALL-UNNAMED
> --add-opens
> javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED
> --add-opens
> javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.binding=ALL-UNNAMED
> --add-opens
> javafx.base/com.sun.javafx.event=ALL-UNNAMED
> --add-opens
> javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
> --add-opens
> javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
> --add-exports
> javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
> --add-exports
> javafx.controls/com.sun.javafx.scene.control=com.jfoenix
> --add-exports
> javafx.base/com.sun.javafx.binding=com.jfoenix
> --add-exports
> javafx.base/com.sun.javafx.event=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.stage=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene.text=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.geom=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.util=com.jfoenix
> --add-exports
> javafx.graphics/com.sun.javafx.scene.traversal=com.jfoenix
> ```

BIG BIG BIG THANK YOU! IT TOOK ME FOREVER TO FIND THIS AND TO ACTUALLY UNDERSTAND IT! FINALLY ANSWER IS HERE! thanks!

**Comment by Bensmed** [comment]
> > Hey, have you figured out what export should be? I have the same problem but with javafx.graphics library
> 
> I was able to fix all my exports by reading the errors from stack trace. MY SOLUTION for the views that I used in my project are as follows :
> 
> [StackOverflow](https://stackoverflow.com/questions/53037442/how-to-fix-jfoenix-modules-with-javafx-11)
> 
> --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
> --add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
> --add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
> --add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
> --add-exports javafx.base/com.sun.javafx.event=com.jfoenix

Thanks! , that worked for me <3.
