### ISSUE TITLE
JFXTextField problem getFocusColor

### ISSUE THREAD

**Issue by bigenergy** [jfoenixadmin/JFoenix#875]
```
2018.11.14 02:10:29 [ERROR] java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/jfoenix/controls/JFXTextField.getFocusColor()Ljavafx/scene/paint/Paint; @25: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'javafx/scene/paint/Paint' (from method signature)
  Current Frame:
    bci: @25
    flags: { }
    locals: { }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 2ab4 0025 c700 0b12 01b8 0050 a700 0d2a
    0x0000010: b400 25b6 0049 c000 21b0
  Stackmap Table:
    same_frame(@15)
    full_frame(@25,{},{Object[#18]})

        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructors(Class.java:1651)
        at sun.reflect.misc.ConstructorUtil.getConstructors(ConstructorUtil.java:43)
        at javafx.fxml.JavaFXBuilderFactory.scanForConstructorAnnotations(JavaFXBuilderFactory.java:216)
        at javafx.fxml.JavaFXBuilderFactory.getBuilder(JavaFXBuilderFactory.java:143)
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1004)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at java.lang.invoke.MethodHandleImpl$BindCaller$T/1020935190.invoke_V(MethodHandleImpl.java:1258)
        at jdk.nashorn.internal.scripts.Script$Recompilation$19$1331A$\^eval\_.loadFXML(<eval>:47)
        at jdk.nashorn.internal.scripts.Script$Recompilation$3$377A$\^eval\_.start(<eval>:24)
        at ru.gravit.launcher.jXH5oo51GTjDWWEcEQe7vUMa$$NashornJavaAdapter.start(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        ... 1 more

```

**Comment by bigenergy** [comment]
<JFXTextField id="login" focusColor="#1a9051" layoutX="264.0" layoutY="257.0" prefHeight="27.0" prefWidth="221.0" promptText="Login" unFocusColor="#b9b5b5" />

**Comment by schlegel11** [comment]
Hi,
I can't reproduce the issue.
Do you have an code example? 

Greetings
