### ISSUE TITLE
NPE on call to JFXCheckbox.setSelected

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#904]
Hi, 
I am using jfoenix v8.0.7.

Sometimes (explained later), when clicking over a jfxcheckbox it throws an NPE with a null message. This usually happens when the checkbox object exists but not shown for a while. For example, when I add the checkbox to a context menu and hide the menu after a while; therefore, I would say the reason is that the component's skin (JFXCheckBoxSkin) is not correctly reacting to its disposal. In other words, the checkbox has a skin which is replaced by another new skin when it is getting visible . So, the checkbox creates another skin on re-shown. However, the old skin which is no disposed accordingly, is still listening to the control (the checkbox) and tries to updateRippleColor when selectedProperty is changed (see JFXCheckBoxSkin.java:90).

Would you please check and resolve this issue if possible.
Here is the partial stacktrace for the bug:

java.lang.NullPointerException: null
	at com.jfoenix.skins.JFXCheckBoxSkin.updateRippleColor(JFXCheckBoxSkin.java:122)
	at com.jfoenix.skins.JFXCheckBoxSkin.lambda$new$0(JFXCheckBoxSkin.java:90)
	at com.jfoenix.skins.JFXCheckBoxSkin$$Lambda$1.invalidated(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.scene.control.CheckBox.setSelected(CheckBox.java:156)

**Comment by jfoenixadmin** [comment]
@aminabs  can you provide SSCCE for this issue ?
