### ISSUE TITLE
JFoenix 8.0.8 does not seem to be compatible with ProGuard

### ISSUE THREAD

**Issue by cbrnrd** [jfoenixadmin/JFoenix#947]
I have a project where I am using JFoenix via Gradle (`compile 'com.jfoenix:jfoenix:8.0.8'`). When I try to obfuscate the compiled fatJar, ProGuard fails with an error:
```
$ java -jar proguard.jar @rules.pro
ProGuard, version 6.0.3
Reading program jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar]
Reading library directory [C:\Program Files\Java\jdk1.8.0_201\jre\lib]
Preparing output jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0-obf.jar]
  Copying resources from program jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar]
Error: Can't write [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0-obf.jar] (Can't read [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar] (Duplicate jar entry [com/jfoenix/animation/JFXNodesAnimation$$Lambda$1.class]))
```
I've been trying to figure this out for a few days and this is the closest I can get to success. Anybody have any ideas?

#### OS
Windows 10

#### JDK Version
Oracle 1.8.0_201

#### ProGuard version
ProGuard, version 6.0.3

#### JFoenix version
8.0.8

## rules.pro
```
-injars asta-2.0.jar
-outjars asta-2.0-obf.jar
-target 1.8
-libraryjars "C:\Program Files\Java\jdk1.8.0_201\jre\lib"
-overloadaggressively
-keep class com.jfoenix.**.**.** {*;}
-dontwarn
-obfuscationdictionary ..\..\obfuscation-dictionary.txt
-classobfuscationdictionary ..\..\windows-dict.txt
-keep class * { public static void main(java.lang.String[]);}
-keep class Server.ClientObject {*;}
-optimizationpasses 3
-allowaccessmodification
-keepparameternames
-dontnote
```

**Comment by cbrnrd** [comment]
Here is a hexdump of the end of the JAR (when ProGuard stops writing):

```
$ cat asta-2.0.jar | xxd | tail -n 20
00000230: 502c cd03 cb1d 8670 a9dc 5110 c392 8c08  P,.....p..Q.....
00000240: 1405 1216 6308 214e 2617 5e63 86ec cce4  ....c.!N&.^c....
00000250: cbae bc8f 73df f4a6 2e5c bd55 0929 86ed  ....s....\.U.)..
00000260: 7f06 2361 8de2 18f9 e1f8 9ca1 d618 76e7  ..#a..........v.
00000270: 6ebe fd5b ef86 1828 83ac 8c34 720c 71df  n..[...(...4r.q.
00000280: b8c5 75d7 76ae d4bf 6ccb 3fcc 1a9c 4043  ..u.v...l.?...@C
00000290: e424 cb94 4e81 2172 4033 246b 5444 4059  .$..N.!r@3$kTD@Y
000002a0: d19d 12d9 d14f 1126 8d38 52b6 a8ca 5015  .....O.&.8R...P.
000002b0: a2b7 5cb9 c772 a57a 87c4 0dc4 4513 6325  ..\..r.z....E.c%
000002c0: 6072 01a3 546e 91a8 be60 f501 799f 8a61  `r..Tn...`..y..a
000002d0: 1d1b 0195 2667 26b4 2784 cec9 6df3 da43  ....&g&.'...m..C
000002e0: f00e 504b 0304 0a00 0008 0800 4e59 7e4d  ..PK........NY~M
000002f0: 340c e3fd 5c01 0000 8c02 0000 3700 0000  4...\.......7...
00000300: 636f 6d2f 6a66 6f65 6e69 782f 616e 696d  com/jfoenix/anim
00000310: 6174 696f 6e2f 4a46 584e 6f64 6573 416e  ation/JFXNodesAn
00000320: 696d 6174 696f 6e24 244c 616d 6264 6124  imation$$Lambda$
00000330: 322e 636c 6173 738d 524b 4bc3 4018 9ced  2.class.RKK.@...
00000340: c3d8 18db 5aed 4bab bd04 ece3 10db 9b54  ....Z.K........T
00000350: 8422 1691 a2b7 a2c7 6d9a d694 3681 184a  ."......m...6..J
00000360: fd57 0a                                  .W.
```

**Comment by DropSnorz** [comment]
I don't know much about proguard. Have you tried with `-verbose` option ?
I'm curious, do you know if the following two lines are equivalent ?
```bash
-keep class com.jfoenix.**.**.** {*;}
-keep class com.jfoenix.** {*;}
```

**Comment by cbrnrd** [comment]
Here is the output with the `-verbose` option:
```
ProGuard, version 6.0.3
Reading input...
Reading program jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar]
Reading library directory [C:\Program Files\Java\jdk1.8.0_201\jre\lib]
Initializing...
Ignoring unused library classes...
  Original number of library classes: 31511
  Final number of library classes:    1074
Backporting class files...
  Number of converted string concatenations:     0
  Number of converted lambda expressions:        0
  Number of converted static interface methods:  0
  Number of converted default interface methods: 0
  Number of replaced Java 7+ method calls:       0
Inlining subroutines...
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 980
  Final number of program classes:    980
Optimizing (pass 1/3)...
  ... snip ...
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 980
  Final number of program classes:    980
Optimizing (pass 2/3)...
  ... snip ...
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 980
  Final number of program classes:    980
Optimizing (pass 3/3)...
  ... snip ...
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 980
  Final number of program classes:    980
Obfuscating...
Setting target versions...
Preverifying...
Writing output...
Preparing output jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0-obf.jar]
  Copying resources from program jar [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar]
java.io.IOException: Can't write [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0-obf.jar] (Can't read [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar] (Duplicate jar entry [com/jfoenix/animation/JFXNodesAnimation$$Lambda$1.class]))
        at proguard.OutputWriter.writeOutput(OutputWriter.java:202)
        at proguard.OutputWriter.execute(OutputWriter.java:89)
        at proguard.ProGuard.writeOutput(ProGuard.java:515)
        at proguard.ProGuard.execute(ProGuard.java:210)
        at proguard.ProGuard.main(ProGuard.java:572)
Caused by: java.io.IOException: Can't read [E:\Backup stuff\Code\IdeaProjects\Asta\build\libs\asta-2.0.jar] (Duplicate jar entry [com/jfoenix/animation/JFXNodesAnimation$$Lambda$1.class])
        at proguard.InputReader.readInput(InputReader.java:214)
        at proguard.InputReader.readInput(InputReader.java:184)
        at proguard.OutputWriter.writeOutput(OutputWriter.java:191)
        ... 4 more
Caused by: java.io.IOException: Duplicate jar entry [com/jfoenix/animation/JFXNodesAnimation$$Lambda$1.class]
        at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:155)
        at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:120)
        at proguard.io.JarWriter.createOutputStream(JarWriter.java:137)
        at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:110)
        at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:110)
        at proguard.io.ClassDataEntryWriter.createOutputStream(ClassDataEntryWriter.java:93)
        at proguard.io.ExtraDataEntryWriter.createOutputStream(ExtraDataEntryWriter.java:135)
        at proguard.io.IdleRewriter.read(IdleRewriter.java:49)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
        at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
        at proguard.io.JarReader.read(JarReader.java:83)
        at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
        at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
        at proguard.InputReader.readInput(InputReader.java:210)
        ... 6 more
```

Regarding `**.**.** {*;}` vs `**` it should be the same. The double-asterisk in the package means every class under every package under that top-level package is kept.

**Comment by jfoenixadmin** [comment]
Hi @cbrnrd,
I'm not a ProGuard expert, but could it be that you are referencing JFoenix jar more than once in your project?

**Comment by cbrnrd** [comment]
@jfoenixadmin I've decompiled the jar to check just that and I'm sure. JFoenix is the only dependency in my project, so there couldn't be any other deps referencing it. If you mean am I importing it more than once, then yes.

**Comment by jfoenixadmin** [comment]
yes multiple imports might be the cause

**Comment by cbrnrd** [comment]
I'll test it and let you know.

**Comment by cbrnrd** [comment]
It didn't change anything, still the same error trace. I also tried adding 
```
-dontshrink
-dontobfuscate
-dontoptimize
```

to the rules, but it did nothing. 

Is com.jfoenix.animation.JFXNodesAnimation the only abstract class in JFoenix? That might be causing something weird to happen within proguard.
