### ISSUE TITLE
IllegalStateException when clicking JFXButton

### ISSUE THREAD

**Issue by HelloWorld017** [jfoenixadmin/JFoenix#97]
When I click a JFXButton, creating ripple gives me an IllegalStateException.

Stacktrace:
```
Exception in thread "Thread-19" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-19
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.scene.Scene.addToDirtyList(Unknown Source)
	at javafx.scene.Node.addToSceneDirtyList(Unknown Source)
	at javafx.scene.Node.impl_markDirty(Unknown Source)
	at javafx.scene.shape.Shape.impl_markDirty(Unknown Source)
	at javafx.scene.Node$MiscProperties$4.invalidated(Unknown Source)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.scene.Node.setCacheHint(Unknown Source)
	at com.jfoenix.transitions.CachedTransition.starting(CachedTransition.java:63)
	at com.jfoenix.transitions.CachedTransition$1.changed(CachedTransition.java:47)
	at com.jfoenix.transitions.CachedTransition$1.changed(CachedTransition.java:43)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.animation.Animation$AnimationReadOnlyProperty.set(Unknown Source)
	at javafx.animation.Animation$AnimationReadOnlyProperty.access$800(Unknown Source)
	at javafx.animation.Animation.setStatus(Unknown Source)
	at javafx.animation.Animation.impl_start(Unknown Source)
	at javafx.animation.Animation.play(Unknown Source)
	at com.jfoenix.controls.JFXRippler.resetOverLay(JFXRippler.java:336)
	at com.jfoenix.controls.JFXRippler.access$400(JFXRippler.java:61)
	at com.jfoenix.controls.JFXRippler$RippleGenerator.lambda$null$120(JFXRippler.java:261)
	at com.jfoenix.controls.JFXRippler$RippleGenerator.access$lambda$2(JFXRippler.java)
	at com.jfoenix.controls.JFXRippler$RippleGenerator$$Lambda$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by jfoenixadmin** [comment]
plz use the latest version of JFoenix, the version you are using is 4 months old.
you can download the latest version using the following link:

http://www.jfoenix.com/download/jfoenix.jar

**Comment by eby73** [comment]
cannot download jar file from primary link, please give me mirror link
