### ISSUE TITLE
Setting the body of JFXDialog with JFXPasswordField throws a NullPointerException

### ISSUE THREAD

**Issue by MagicalSheep** [jfoenixadmin/JFoenix#976]
I'm trying to get the password from the user by using JFXDialog. I have built a JFXDialog and a JFXPasswordField. However, when I tried setting the body of JFXDialog with JFXPasswordField, which was alright in JFoenix 8 ( JDK 8 ), it threw an exception. I am using JDK 12 and JFoenix 9.0.8 now.

        JFXButton ok = new JFXButton("OK");
        JFXPasswordField passwordField = new JFXPasswordField();
        ok.setPrefSize(70, 35);
        JFXDialogLayout content = new JFXDialogLayout();
        content.setHeading(new Text("Password"));
        content.setBody(passwordField);
        content.setActions(ok);
        JFXDialog dialog = new JFXDialog(root, content, JFXDialog.DialogTransition.BOTTOM);
        dialog.show();

Here are the exception messages:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException

	at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109)
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93)
	at javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.scene.Parent.layout(Parent.java:1206)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:562)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by jfoenixadmin** [comment]
Hi @MagicalSheep,
Try using the latest version of JFoenix, I was not able to reproduce using the current JFoenix repo build.
If you were able to reproduce using the latest build, then either wait for the next build or you have to build JFoenix manually.

Regards,
